### ISSUE TITLE
Enable all image to show the revision

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1026]
Other images, such as zk, bk and wk, are able to show the revision...

- [x] Enable configurator image to show the revision (#1232)
- [x] Enable manager image to show the revision (#1247)
- [x] Enable streamapp image to show the revision (#1275)

**Comment by chia7712** [comment]
@saivirtue Do you want to take over the last sub-task ?

**Comment by saivirtue** [comment]
> @saivirtue Do you want to take over the last sub-task ?

Sure, will be accomplished in #1213 also

**Comment by chia7712** [comment]
> will be accomplished in #1213 also

Please DON'T arbitrary include other issues in another totally unrelated issue...

**Comment by chia7712** [comment]
Especially the issue does happen after your origin one. It is bad to see a opening issue and then include it in a working one.

**Comment by saivirtue** [comment]
> Please DON'T arbitrary include other issues in another totally unrelated issue...

#1213 is meant to **change the streamApp image** to support jmx, which will migrate the file to support **ohara.sh** (and hence, support version)
I don't see the arbitrary here...

**Comment by chia7712** [comment]
@saivirtue Please add your name to assignee if you want to take over the last tasks.

**Comment by saivirtue** [comment]
all done.
