### ISSUE TITLE
Update sbt build

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1044]
According #832 discussion, sbt configuration can be provide development assistance.
This would be helpful if collaborator comes from scala community.

But sbt configuration in ohara totally out of date currently, we need to update it.
Things we need to do:

- [x] update all dependencies(#893)
- [x] add ohara-metrics module(#893)
- [x] run junit from sbt(#893)
- [x] generate VersionUtis.java dynamically(#893)
- [x] license check and auto-fix(#1242)
- [x] codestyle check and auto-fix(#1242)
- [ ] tests jvm setting and output log
- [ ] assembly jar and uber jar
- [ ] Document for Sbt build

**Comment by vitojeng** [comment]
Due to #3144, close now.
