### ISSUE TITLE
As a user, I hope to have an abstract CSV Connector that allows me to easily customize the Connector to read or write CSV files from different file systems.

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1048]
- [x] design TextSourceTask  (issue #1147 )
- [x] implement TextSourceTask & Tests  (issue #1137 )
- [x] refactor FTPSourceConnector to extends TextSourceTask & Tests  (issue #1137 )
- [x] design a abstract sink connector for text file #1148 
- [x] eXtract an abstract class for csv sink task from HDFSSinkConnector #1136 
- [x] refactor HDFSSinkTask to extend CsvSinkTask #1739 
- [x] refactor FtpSinkTask to extend CsvSinkTask #2079

**Comment by eechih** [comment]
Moving this to 0.7. I need more time to design and implementation.
