### ISSUE TITLE
身為一個開發者，我希望能夠更容易的了解StreamApp如何開發

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1053]
- [x] Refactor StreamApp Java API to be more suitable for current data model (issue #474)
- [x] Add more different samples (at least three) for streamApp (issue #1253)
- [x] Add streamApp development document (issue #1283)
