### ISSUE TITLE
Refactor hdfs sink connector to use the new metadata API

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1097]
- [x] Rewrite hdfs sink connector component and use the new API (#1274)
- [x] Wrap hdfs sink connector with final form (#1297)
- [x] Use material UI to create hdfs sink component (#1304 )

required by #1049

**Comment by konekoya** [comment]
related #518
