### ISSUE TITLE
Support jdbc.Table type

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1107]
copy from #1102
As I mentioned before, this solution requires user to deploy the driver to Configurator for database. And it introduces many extra “know how” to user and it makes unfriendly use.

To resolve the gap, the backend needs to address many tasks.

Introduce jdbc.Table type
A official helper connector used to fetch the table information
Establish connection between configurator and worker cluster
The side-effect is a huge latency but user don’t worry about the jar deployment to configurator.

- [x] enable Validator connector to fetch table (#1138)
- [x] QueryRoute should fetch table via Validator connector (#1144)
- [x] add JDBC_TABLE type to connector setting (#1145)
- [x] remove postgresql driver from Configurator image (#1146)

the improvement for UI is traced by #1149

**Comment by jackyoh** [comment]
jdbc source connector 的 code 需要修改嗎？

**Comment by chia7712** [comment]
> jdbc source connector 的 code 需要修改嗎？
Later

**Comment by jackyoh** [comment]
ok

**Comment by chia7712** [comment]
all done!!!
