### ISSUE TITLE
Enable exactly once in ohara

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1133]
Data consistency and availability is high priority for users, we need to check and implement this feature to our ohara.

- [ ] Check and implement exactly in streamApp
- [ ] Check and implement exactly in connector
- [ ] Check and implement exactly in shabondi
- [ ] Implement performance benchmark of ohara
