### ISSUE TITLE
Refactor FTP Source connector to use the new metadata API

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#1168]
- [x] Rewrite ftp source connector component and use the new API #1177 
- [x] Wrap ftp source connector with final form #1289
- [x] Wrap ftp source connector metadata table type with final form #1303 
- [x] Use material UI to create ftp source component #1306 

required by #1049
