### ISSUE TITLE
Implement metrics to stream

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1190]
This issue will finish the following tasks:
- [x] add `metrics` interface into streamApp module (move to #1198)
- [x] enable streamApp image using jmx (move to #1213)
- [x] add metrics data into stream route api (move to #1259)
~- [ ] enable default jmx~ (move to #1330)

required by #1054

**Comment by saivirtue** [comment]
all tasks are done.
