### ISSUE TITLE
Migrate upload jar api of streamApp to JarRoute api

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1252]
StreamApp upload api support:
- upload multiple jars
- delete specific jar
~- rename specific jar~ (question in #1426)

And the above APIs are similar with JarRoute api. This issue is intend to ease the duplicate work of jar operations.

**We need to finish the following tasks**
- [x] check if there is any issue for the migration work
- [x] add the same operation to JarRoute (#1427)
-- support `group` in jarRoute
- [x] apply same rule from StreamRoute jar api to JarRoute (#1443)
- [x] move the used api from /stream/jar to /jar in manager (move to #1560)
- [x] remove the stale stream api (move to #1560)

**Comment by chia7712** [comment]
Nice one. Is this issue too big to complete in 0.5 ? If not, please remove umbrella label and attach 0.5 label.

**Comment by saivirtue** [comment]
This umbrella issue require @konekoya to accomplish together. Will check the available time of him.
And also, this issue has multiple tasks, as we discuss the umbrella usage, I think the umbrella label should be fine. `v0.5.0` label will be added after check.

**Comment by chia7712** [comment]
> this issue has multiple tasks, as we discuss the umbrella usage

An umbrella should be used to include multiples issues **and** all of them can be resolved in a version release. Filing many **trivial** issue with **nothing** description is not good to us, and it is not convenient to trace story from one issue to another issue. Especially, all stories are record in root one...

**Comment by chia7712** [comment]
> This umbrella issue require @konekoya to accomplish together.

And it would be better to update APIs without **breaking** the legacy one. We had updated many APIs with this way, and you can file a issue to trace the stale APIs. (for example #518). As a backend developer, we can't always wait/block frontend developer...

**Comment by saivirtue** [comment]
> Is this issue too big to complete in 0.5 ? If not, please remove umbrella label

> An umbrella should be used to include multiples issues and all of them can be resolved in a version release. 

Are these two sentences contradict each other?

This issue is just want to change the api without any harmful side-effect:
1. add the same operation to JarRoute api (**preserve old function**)
2. move the used api from /stream/jar to /jar in manager (**move old api to new api**)
3. remove the stale stream api (**clean old api**)

at any rate, task 1 could be implemented without waiting

**Comment by chia7712** [comment]
> Are these two sentences contradict each other?

" all of them can be resolved " -> " all of them can't be resolved "
