### ISSUE TITLE
Redesign the pipeline environment creation

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1336]
**Description**
Currently, OharaStream has integrated many different types of clusters, such as zookeeper cluster, broker cluster, worker cluster. We also have provided a great simple way(RESTful API) to create these type of clusters. But for most users, this is still too hard to understand the whole BigData related environment.

Hence, we need to simplify the process of pipeline environment creation by making these clusters creation automatically.

**Todo items**

- [x] A simple proposal, include wireframe(#1050)
  - [x] 產出一份 Proposal 文件 (Issue #1082)
  - [x] 產出一份 Wireframe 文件 (Issue #1081)
- [x] Implement tasks
  - [x] Design pipeline workspace pages(#1425)
  - [x] Implement pipeline workspace pages(#1469)

**Comment by konekoya** [comment]
Some refactoring will be done in #1538 :)

**Comment by vitojeng** [comment]
All tasks of **pipeline workspace** already done.
close now.
