### ISSUE TITLE
User can upgrade worker cluster plugins

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1343]
There cannot add or upgrade the connector after worker cluster created currently.
The user will need:
* Add a new custom connector to the current worker cluster.
* Upgrade or remove a custom connector in the worker cluster.

**To do items**
- [x] Proposal: Upgrade worker cluster plugins(#1364)
- [x] Add plugins tab in workspace and inside overview tab (#2482 )
- [x] Upgrade workspace with updated plugins (#2483)
- [x] Restore workspace if the upgrade failed (#2484)
- [x] Display plugin and file different in overview (#2483)

**Comment by vitojeng** [comment]
@konekoya 
Please update the isse decscription to describe the implementation items. :)
