### ISSUE TITLE
[phase2] Enable exactly once in ohara

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1357]
This is the follow-up of #1133

- [ ] Check and implement exactly in connector
- [ ] Check and implement exactly in shabondi
- [ ] Implement performance benchmark of ohara
