### ISSUE TITLE
Test configurator's RESTful APIs from frontend

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1370]
- [x] Expose a fake mode configurator for frontend (#1444)
- [x] Ensure these tests can be run on Jenkins (#1495)
- [x] Use cypress test RESTful APIs with services and nodes page (#1374 )
- [x] Use cypress test RESTful APIs with pipelines page (#1473 )
Ref #1051

**Comment by konekoya** [comment]
@wu87988622 Feel free to add more tasks to tackle this issue :)

**Comment by chia7712** [comment]
all tasks have been completed!!! close this now. @wu87988622 @konekoya Thanks for all contribution!!!

**Comment by konekoya** [comment]
@chia7712 Hmm, I think we should do the demo first before closing the issue since it's (used to be) a story? Should we add a label to indicate this as an umbrella

**Comment by chia7712** [comment]
@konekoya feel free to reopen this issue
