### ISSUE TITLE
Integrate Sphinx & Read the Docs

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1385]
[Sphinx](http://www.sphinx-doc.org/) is a tool that makes it easy to create documentation.
[Raed the Docs](https://readthedocs.org/) is a hosting for docs automating building, versioning.

- [x] Integrate with Read the docs(#1441)
  - [x] Markdown format support
  - [x] Auto-updating(post-commit hook)
  - [x] Multiple versions support(latest, stable...)
- [x] Fix break links(#1463, #1478)
- Move all source files into `docs/src`(#1458)
  - [x] Move all markdown files into `docs/src`
  - [x] Reduce image files and move into **docs/src/images** folder
- [x] Use [sphinx_rtd_theme](https://sphinx-rtd-theme.readthedocs.io/en/stable/index.html) theme(#1459)
- [x] Enable **sphinx.ext.extlinks** instead to avoid absolute path.
- [x] Rename doc-site domain from `https://oharastream.readthedocs.io` to `https://ohara.readthedocs.io`(#1664)

<details><summary>Reference:</summary>

* [An introduction to Sphinx and Read the Docs for Technical Writers](http://www.ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers/)
* Cheatsheet: [A two-page rst cheatsheet](http://github.com/ralsina/rst-cheatsheet/raw/master/rst-cheatsheet.pdf)
* Tutorial
  * [Sphinx Tutorial](https://sphinx-tutorial.readthedocs.io/)
  * [Brandon’s Sphinx Tutorial](https://buildmedia.readthedocs.org/media/pdf/brandons-sphinx-tutorial/latest/brandons-sphinx-tutorial.pdf)
* Theme
  * [HTML theming support](http://www.sphinx-doc.org/en/stable/theming.html)
  * [Sphinx Themes](https://sphinx-themes.org/)
</details>

**Comment by vitojeng** [comment]
@chia7712 Please help to review PR again, so I can move on.

**Comment by vitojeng** [comment]
@chia7712, @eechih , @saivirtue, @konekoya 

Since we move all documents into **docs** folder. It would be better that rename **docs** to **ohara-docs**. Jenkins could help the PR to add **docs** label if the PR contain document change.

Any thought?

**Comment by chia7712** [comment]
Jenkins is able to attach the label for docs regardless of folder name :)

At any rate, renaming it to ohara-docs is ok to me.

**Comment by vitojeng** [comment]
> Jenkins is able to attach the label for docs regardless of folder name :)
> 
> At any rate, renaming it to ohara-docs is ok to me.

Got it. 
If the prefix is not necessary for appending a label, I intend to stay the original name.

**Comment by vitojeng** [comment]
OharaStream document link: 
https://oharastream.readthedocs.io/en/latest/

All integration tasks are done.

**Comment by vitojeng** [comment]
Reopen for fix broken links

**Comment by vitojeng** [comment]
done

**Comment by vitojeng** [comment]
Reopen to fix broken links

**Comment by vitojeng** [comment]
Rename docs-site domain to `https://ohara.readthedocs.io`
