### ISSUE TITLE
[Phase1] Support dead cluster concept

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1438]
this is a follow-up of #1220.

To introduce the following concept (thanks @chia7712 @vitojeng ):
<details><summary>Conclusions</summary>

1. cluster (zk, bk, wk, streamApp) should still **active** (running) even if partial nodes are dead.
2. cluster should be considered **dead** if and only if all the belonging nodes are dead.
3. cluster will be **removed** if and only if all belonging containers are gone (removed)
4. whatever status of nodes, cluster should **always be able to fetch** from collie.
4.1. cluster(name: String) can be fetched even if all containers are “exited” (but still existed).
5. clusterInfo support **deadNodes** and **status** fields. 
6. Ohara Manager could support show the added fields (status, deadNodes)
</details>

We have works to do :
- [x] dead containers should still be able to fetch (#1350)
- [x] cluster should be removed if and only if all belonging containers are gone (#1350)
- [x] cluster should be able to fetch from collie if containers still exist (running or dead) (#1350)
- [x] support ~status~ and deadNodes fields in clusterInfo ~(#1545)~(#1556)
-- we need support more meaningful "status", move to #1532
~- [ ] support show deadNodes and status for cluster information in UI~ move to #1532

**Comment by saivirtue** [comment]
/cc to @eechih @wu87988622 @vitojeng @konekoya @chia7712 @jackyoh 
these changes will affect some behaviors of backend and frontend, if there were concerns or questions, please comment here :)

**Comment by saivirtue** [comment]
the remaining tasks will move to [phase 2](https://github.com/oharastream/ohara/issues/1532), close this issue now.

**Comment by chia7712** [comment]
@saivirtue 麻煩revert PR 因為

1. commit message格式錯誤
2. build broken (see https://builds.is-land.com.tw/job/PreCommit-OHARA/2939/artifact/checks/check_build.log)

**Comment by saivirtue** [comment]
> @saivirtue 麻煩revert PR#1545 因為 commit message格式錯誤
> 
> build error 不是這個議題造成

Ok.
