### ISSUE TITLE
Implement pipeline workspace pages

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1469]
- [x] Implement workspace list page @konekoya (#1475)
- [x] Wire up routes and basic page structure for workspace @konekoya  (#1507)
- [x] Add sorting function in table component @wu87988622 (#1512 )
- [x] Add tooltip in tables' action icons @wu87988622(#1512)
- [x] Implement overview page @konekoya (#1572)
- [x] Implement nodes page @wu87988622 (#1558 )
- [x] Implement topics page @konekoya (#1530)
- [x] Implement stream apps page @wu87988622 (#1542)

Design mockups: #1425 
Parent issue: #1336

**Comment by konekoya** [comment]
Added a few todos and these tasks should be finished by the end of this week :)

/cc @wu87988622

**Comment by chia7712** [comment]
Which issue or PR is related to jar uploading?

**Comment by konekoya** [comment]
> Which issue or PR is related to jar uploading?

@chia7712  Are you talking about uploading custom connector and DB drivers?

If so, it's still in the same modal but with a different name: New workspace :)

**Comment by konekoya** [comment]
Which will be implemented in the __workspace list page__ sub-task

**Comment by konekoya** [comment]
Thanks for the help @wu87988622. Let's close this issue off and move on to work on #1538
