### ISSUE TITLE
Docs improvement

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1486]
**Todo items**
- [x] Add .rst & .py file license header support(#1884)
- [x] Provide `branch` name in gradle.properties (#1867)
- [x] Convert to **rst** format(#1840)
- [x] Avoid `WARNING` when build the docs(#1988)
- [x] Remove all hard code internal links(#1987)
- [x] Document: How to build Ohara docs(#1984)
- [x] Document: A quick example for rst document writing(#2073) 
- [x] Introduce Quickstart VM(#2440)
- [x] Document: **Quick start**(oharastream/ohara-quickstart#3)

**Comment by vitojeng** [comment]
done
