### ISSUE TITLE
Add global rule to all JSON unmarshalling

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1498]
This is beyond akka unmarshalling that offers more strict checks to input string. For example,
1. string can't be empty
1. connection port must be [0, 65535)
1. bind port must be [1024, 65535)
1. null array is equal to empty array

- [x] Add global rule to all JSON unmarshalling and apply it to Ftp APIs (#1535) (@chia7712)
- [x] apply global JSON unmarshalling to Query APIs (#1541) (@chia7712)
- [x] apply global JSON unmarshalling to HDFS APIs (#1539) (@jackyoh)
- [x] apply global JSON unmarshalling to JDBC APIs (#1552) (@jackyoh)
- [x] apply global JSON unmarshalling to Topic APIs (#1543) (@chia7712)
- [x] apply global JSON unmarshalling to Connector APIs (#1559) (@chia7712)
- [x] apply global JSON unmarshalling to Pipeline APIs (#1568) (@chia7712)
- [x] apply global JSON unmarshalling to Zookeeper APIs (#1569) (@chia7712)
- [x] apply global JSON unmarshalling to Broker APIs (#1588) (@chia7712)
- [x] apply global JSON unmarshalling to Worker APIs (#1608) (@chia7712)
- [x] apply global JSON unmarshalling to Streamapp APIs (#1630) (@saivirtue)
~- [ ] apply global JSON unmarshalling to Jar APIs (@saivirtue)~
-- jarAPI is used to upload file ; there is no rule could apply to
- [x] apply global JSON unmarshalling to Validation APIs (#1587) (@chia7712)
- [x] apply global JSON unmarshalling to Node APIs (#1557) (@saivirtue)

**Comment by saivirtue** [comment]
> 3. bind port must be (0, 65535)

May be we could set this more restrictive, exclude the system reserved ports to avoid possible conflict?
[1024, 65525]

**Comment by chia7712** [comment]
> [1024, 65525]

It is possible to meet the service is able to bind port below 1024. For example, ftp info. 

However, adding a more strict limit to port for other APIs is great. I will add this rule!

**Comment by chia7712** [comment]
@saivirtue @jackyoh @eechih I will complete the infra of this issue, and there are a lot of sub PRs need to complete. Please give me a hand to iron out those sub-issues :)

**Comment by jackyoh** [comment]
OK, 收到. 我先認養 HDFS, JDBC, Zookeeper, Broker, Worker APis. 是參考 #1498 的寫法嗎？

**Comment by chia7712** [comment]
> 我先認養 HDFS, JDBC, Zookeeper, Broker, Worker APis.

麻煩在該工作後面補上你自己的名字 以及把自己加到assignee裡面

>是參考 #1498 的寫法嗎？

yep

**Comment by chia7712** [comment]
@jackyoh I will take over the PR of zookeeper API in order to complete this issue in 0.6

**Comment by jackyoh** [comment]
> @jackyoh I will take over the PR of zookeeper API in order to complete this issue in 0.6

OK, 收到了. 我會盡快把 Broker 和 Worker 做完

**Comment by chia7712** [comment]
@saivirtue I take over the sub task "Validation" :)

**Comment by chia7712** [comment]
@jackyoh @saivirtue I have enough free cycle to complete remaining sub-tasks. Please feel free to assign the sub-task to me :)

**Comment by saivirtue** [comment]
> @jackyoh @saivirtue I have enough free cycle to complete remaining sub-tasks. Please feel free to assign the sub-task to me :)

/cc @chia7712 
streamApi is working now
jarApi is blocked by #1286 :(

**Comment by jackyoh** [comment]
> have enough free cycle to complete remaining sub-tasks. Please feel free to assign the sub-task to me :)

OK, Thank you.

**Comment by chia7712** [comment]
all done!!! @jackyoh @saivirtue Thanks for great helps!!!
