### ISSUE TITLE
[Phase2] Support dead cluster concept

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1532]
This is phase 2 of #1438 
For cluster, we should have more meaningful status beside "running" and "failed" ; We should
- [x] define the cluster status enumeration and rules (move to #1544)
- [x] save settings to configurator for cluster (zk, bk, wk)  (move to #1544)
- [x] Show status and deadNodes in UI (#3444 )

**Comment by chia7712** [comment]
@saivirtue I'd say our @oharastream/frontend neglect this issue for a long time. please ping them for more discussion :)

**Comment by konekoya** [comment]
Seems like everything is done in the backend? But I'm not quite following about the issue 😅 @saivirtue or @chia7712 would you mind explaining a bit more to me here or we can have a quick meeting to discuss how we can go about it?

**Comment by chia7712** [comment]
@konekoya Please write the conclusion for our discussion :)

**Comment by konekoya** [comment]
Have a quick discussion on the topic with @chia7712 today. 

In the cluster APIs (zookeepers, brokers, and workers) the added field __deadNodes__ will keep track of the dead nodes(nodes that are not running or failed) of the originally assigned nodes from the users. And the __nodeNames__  field will store the nodes no matter a node is running or failed.

For example:

A worker cluster is started and assigned the following nodes

nodeA, nodeB and nodeC

In the API, the nodeNames field should be
```json
"nodeNames": ["nodeA", "nodeB", "nodeC"]
"deadNodes": []
```

Assuming that after the cluster running for a while, and for some reason, __nodeA__ failed. Our API would display something like:

```json
"nodeNames":   ["nodeA", "nodeB", "nodeC"]
"deadNodes": ["nodeA"]
```

Notice that the __nodeNames__ still has all the nodes that were given by the user when initializing the cluster. But the __deadNodes__  value is updated.

For frontend. We will figure out where to display this info to the users and so they can use our logs API to see a dead node's logs and fix the issue.

@chia7712 feel free to add more detail if I have missed something :)

**Comment by chia7712** [comment]
a nit

> In the cluster APIs (zookeepers, brokers, and workers)

and streamapp

and for another thing. the nodeNames will be moved to "settings" (see https://github.com/oharastream/ohara/issues/2438)

**Comment by chia7712** [comment]
@konekoya @wu87988622 any suggestion about showing the dead node?

**Comment by konekoya** [comment]
> @konekoya @wu87988622 any suggestion about showing the dead node?

I'm thinking about putting the info in the workspace, perhaps in the overview pages. I will open a new issue to discuss this matter :)

**Comment by konekoya** [comment]
@vitojeng @chia7712 @eechih I think we should also include this in the new UI, right?

**Comment by eechih** [comment]
> I think we should also include this in the new UI, right?

@konekoya That's right, it will be done in the new UI.

**Comment by vitojeng** [comment]
Great! Thanks for @oharastream/frontend

**Comment by konekoya** [comment]
@eechih Feel free to close or link to issue when it's done :)

**Comment by eechih** [comment]
> Feel free to close or link to issue when it's done

@konekoya OK
