### ISSUE TITLE
[Phase 1] Refactor workspace pages

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1538]
While we're rushing through implementing workspace pages, some of the UIs are still using old components. We should update these components to use material UI just like the rest of the pages.

A couple of things that are already on my radar:

- [x] Replace the old delete modal with Mui dialogs @konekoya (#1627)
- [x] Support multiple nodes when creating a workspace @konekoya (#1634)
- [x] Add topic page end-to-end tests @wu87988622 (#1582 )
- [x] Use the same table style throughout the service tabs @konekoya (#1590)
- [x] Fix overview page layout @konekoya (#1589)
- [x] Use the metrics data in topics list @konekoya  (#1624)
- [x] Do not display PerSource connector in the overview page for now @konekoya (#1623)

**Comment by konekoya** [comment]
Phase one was done. The rest can be found in #1628
