### ISSUE TITLE
[Phase 2] Refactor workspace pages

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1628]
Phase 1 #1538

- [x] Refactor new workspace modal and fix some minor issues (related to #1671) @wu87988622 (#1706 )
- [x] Add unit tests @konekoya 
  - [x] Add workspaces page unit tests (#1667)
  - [x] Add topics and stream apps tab unit tests (#1699)
  - [x] Add nodes tab unit tests (#1811)
  - [x] Add overview page unit tests
- [x] Add more end-to-end tests @wu87988622 (#1746 )
- [x] Better user feedback in new node modal when there's no available node in the list @wu87988622 (#1661 )
- [x] Refactor sort table component making it more reusable @wu87988622 (#1652 )

**Comment by konekoya** [comment]
@wu87988622 we'll be continuing our refactor of workspace pages in this issue
