### ISSUE TITLE
Ohara 0.6.0 Release

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1660]
- [x] Create 0.6 branch (base on last commit of frozen day)
- [x] #1662 Update version of master branch to 0.7.0-SNAPSHOT
- [x] Remove unused (or unnecessary) functions from 0.6 branch (skip this step)
- [x] Add change log to release wiki page
- [x] #1833 Update version of 0.6 branch to 0.6.0
- [x] #1837 修改 0.6 branch 文件的連結為 0.6.0
- [x] Upload Bintray repo
- [x] Add tags to release wiki page
- [x] Add 0.6 binaries to github download
- [x] #1676 Update 0.6 branch's docs version to 0.6
- [x] 設定 jenkins 使 0.6 和 0.7.0-SNAPSHOT 都可以 build code 和測試
- [x] #1791 Create ohara product testing report issue
- [x] 把 0.6 branch 所有程式和文件的版本號修改成 0.6.1-SNAPSHOT

**Comment by vitojeng** [comment]
We should add a doc related task: **Update 0.6 branch's docs version to `0.6`**

**Comment by jackyoh** [comment]
> Update 0.6 branch's docs version to 0.6

OK, 我先加到 describe 的 checkbox 裡

**Comment by jackyoh** [comment]
ping @vitojeng @chia7712 @jackyoh @saivirtue @konekoya @wu87988622
OharaStream 下周要 release 0.6 版, 目前需要徵稿做 release 的 highlight. 

因此 0.6 版功能有需要特別 highlight 的部份, 再寫描述在以下的 comment 裡. 


Thank you!

**Comment by chia7712** [comment]
friendly auto-generated fields - Most fields in Restful APIs, now, is able to generate automatically when the they are ignored. For example, the request used to create a zookeeper cluster in 0.5 is 
```json
{
  "name": "zk",
  "clientPort": 123,
  "peerPort": 444,
  "electionPort": 555,
  "nodeNames": ["n0"]
}
``` 
In 0.6, your request can only carry name and nodeNames to create a zookeeper. 
```json
{
  "name": "zk",
  "nodeNames": ["n0"]
}
```
This graceful auto-fill function is applied to all Restful APIs.

**Comment by saivirtue** [comment]
**StreamApp**: We now support jmx service for streamApp also. [streamApp APIs](https://github.com/oharastream/ohara/blob/0.6/docs/src/rest_interface.md#streamapp) are able to fetch the metrics data of record count (source topic and target topic) by default. See [streamApp guideline](https://github.com/oharastream/ohara/blob/0.6/docs/src/custom_streamapp.md#metrics) for more details.

**Comment by konekoya** [comment]
New workspace pages: 
- Create and deploy services with one single click to multiple nodes
- Add topics, stream apps or even dynamically adding new nodes to a running workspace
- An overview page which gives you more information about a workspace

**Comment by vitojeng** [comment]
New document site: https://ohara.readthedocs.io

**Comment by vitojeng** [comment]
> **StreamApp**: We now support jmx service for streamApp also. [streamApp APIs](https://github.com/oharastream/ohara/blob/0.6/docs/src/rest_interface.md#streamapp) are able to fetch the metrics data of record count (source topic and target topic) by default. See [streamApp guideline](https://github.com/oharastream/ohara/blob/0.6/docs/src/custom_streamapp.md#metrics) for more details.

@jackyoh , @saivirtue  裡面的連結應該連到 document 網站? 不是 source 裡面.

**Comment by jackyoh** [comment]
OK, 我再幫 @saivirtue 修改

StreamApp: We now support jmx service for streamApp also. [streamApp](https://ohara.readthedocs.io/en/0.6/rest_interface.html#streamapp) APIs are able to fetch the metrics data of record count (source topic and target topic) by default. See [streamApp guideline](https://ohara.readthedocs.io/en/0.6/custom_streamapp.html#metrics) for more details.

ping @vitojeng @saivirtue 連結已經改好了, 再幫我確認看看

**Comment by jackyoh** [comment]
我的 highlight 內容如下：
* Refactor the WorkerCollie to K8S and SSH have the same creator logic
* Fix JDBC source connector get the ResultSet data out of memory issue

**Comment by chia7712** [comment]
@jackyoh Could you please eliminate all 0.6.0-SNAPSHOT images from docker hub ? They are useless after releasing 0.6.0

**Comment by vitojeng** [comment]
@chia7712 , @jackyoh 
It seems that remove unused images is a regular task?
If yes, it would be better we have a jenkins job to do this for RM.

**Comment by chia7712** [comment]
> If yes, it would be better we have a jenkins job to do this for RM.

ok. Let me take a look at docker hub APIs
