### ISSUE TITLE
[Phase 1] Migrate all the components to Mui

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1730]
It's about time to migrate all the component to Material UI. This will essentially remove a lot of duplicated components from our codebase as well as applying the same styles across different components :)

- [x] Change toastr to Mui Snackbar #1961 
- [x] Add a loading progress bar to better inform users about the progress of a certain action #1856 
- [x] Refactor node page so it's consistent with others Mui components  #2120 
- [x] Replace all tooltips with Mui's tooltip component (#2195)
- [x] Refactor new topic modal with a better form validation feedback #2099 
- [x] Update unit test with new api and snackbar #2037 
- [x] Refactor pipeline list page with Mui #2147

**Comment by konekoya** [comment]
@wu87988622 Please add sub-tasks for this issue so we can better estimate the overall time of dealing it :)

**Comment by konekoya** [comment]
Thanks for the hard work @wu87988622. I'm going to close this issue for now. And we can continue the work in #2221
