### ISSUE TITLE
Display metrics data in pipeline graph and pages

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1735]
Ref: #642 

- [x] Refactor pipeline new/edit page (#1949)
- [x] Add metrics data in the pipeline graph (#1896)
- [x] Add connector metrics data sidebar (#1956)
- [x] Display metrics with mui's expansion panel (#1960)
- [x] Add an active state to the graph (#1970)
- [x] Support stream app metrics (#1977)
- [x] Re-fetch metrics data while the page is active
