### ISSUE TITLE
Refactor manager's API tests

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1749]
The API tests are now all lived in a single giant file making debugging and tweaking tests extremely hard. We should consider separating the tests into smaller files and removing the shared variables they're using now (hence, less coupling).  

- [x] Add broker delete API test and refactor worker API (#2012)
- [x] Broker API (#1971)
- [x] Refactor topic, container and log API tests (#2014)
- [x] Refactor connector API tests (#2028)
- [x] Refactor node and zookeeper API tests (#2034)
- [x] Enable pipeline API tests (#2052)
- [x] Cleanup services after each API test (#2058) 
- [x] Enable validate and add info API tests (#2059)
- [x] Refactor stream and jar API tests (#2110)

**Comment by konekoya** [comment]
@wu87988622 I'm taking over this issue since I've done a little bit refactoring in #1971 already :) and you can continue your work on #1730
