### ISSUE TITLE
Increase manager's unit test coverage

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1767]
@DavidMi-1 will be dedicated to this issue and help add more unit tests to frontend codebase 💯 

### More tests should go into the following list:

- [x] Add more unit tests to client's API
  - [x] Add unit test to brokerApi (#1773)
  - [x] Fix streamApi unit test (#1784)
  - [x] Add workerApi unit test (#1790)
  - [x] Add validateApi unit test (#1793)
- [x] Component tests
  - [x] Add Logs page unit test (#1841)
  - [x] Nodes
    - [x] Add validate unit test (#1854)

**Comment by konekoya** [comment]
@DavidMi-1 I think it's about time to close this off and move on to #1873 :)
