### ISSUE TITLE
Remove rules field in the pipeline API

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1777]
There's a new field named `flow` in pipeline API and it's meant to replace this `rules` field.

After this, we can remove the rules from the backend API in #1644 

- [x] Use flows field instead of rules field in pipeline API (#2119)
- [x] Use the correct topic keys in connectors (#2136)
- [x] Fix cannot start/stop a connector from pipeline issue (#2141)
- [x] Fix pipeline graph not updating issue when switching between the same type of connector (#2148)
- [x] Fix pipeline connector deletion (#2168)
