### ISSUE TITLE
Refine Node APIs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1809]
The Node APIs is the entrypoint to marshal our distributed envs. With more collie impls and apps, the node interface gets stale and weird. This issue aims to refine Node APIs and it consists of following issue.

- [x] remove --node from Configurator (#1835)
- [x] add "hostname" to node APIs (#1817)
- [x] k8s mode should be able to ignore user name and password (#1859)

**Comment by chia7712** [comment]
All tasks are completed!
