### ISSUE TITLE
Docs: Convert format from markdown(md) to reStructuredText(rst)

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1840]
- [x] Read version from gradle.properties(#1858)
- [x] Initial extlink config(ohara issue, source, kafka issue)(#1858)
- [x] Convert format from markdown(md) to reStructuredText(rst)
  - [x] How to build, Contributing(#1877)
  - [x] Docker, Integration Test, User Guide(#1923)
  - [x] Custom connector, Custom streamapp(#1963)
  - [x] REST Interface, Manager Developer Guide(#1979)
