### ISSUE TITLE
Ohara 0.7.0 Release

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#1868]
### Highlights

- Ohara Manager
  - __Pipeline metrics:__ Ohara manager is now able to display the metrics info in the pipeline! You can view the metrics on each graph and more information on each graph's sidebar as well  (#1735)
  - __Improved workspace creation process:__ we've added a progress bar to better inform users the progress of a workspace creation  (#1856)
  - __Material UI migration (Phase 1):__ we've rewritten some of our UI components with the newly released React Hooks and Material UI library, which erased the inconsistent UI behaviors and stylings from Ohara manager (#1730)
  - __Performance connector__: performance connector has been added and can be used now in the manager's pipeline as one of our officially supported connectors. (#271)
  - __Rewrote unit tests__: we have rewritten most of Ohara manager's unit test suites and gaining more code coverage in this milestone. The rewritten unit tests give us more confidence while avoiding testing the implementation details of the UI. This will help for the future when we're refactoring and adding new features in the frontend. (#1873)

- StreamApp
  - As connector, custom definition is a way to enable user define their own configs and display in UI.(#810 Enhance streamApp to support custom setting)

- Connector
  - We now support official sink task for CSV to easily customize your connector. (#1048) 
  - JDBC Source Connector need to support offset recovery. Avoid restarting JDBC Source Connector database table data not write to the Kafka topic. Please refer issue #1732 
  - an new sink connector - ConsoleSink - is available now. It enables us to print the data to the console. Furthermore, ConsoleSink is able to control the frequency of outputting data. For example, you can require ConsoleSink to print data per 10 seconds. It is useful in reducing the size of log file. (#2184) 
- REST APIs
  - Most objects are able to store tags for user. The tags is useful to represent the "specific" objects. Or you can use tags to save any data you want. Of course, the tags is in json representation as we are in restful world.(#1711 add tags to all objects)
  - Group is an extra index of object. It enables us to make two objects have the same name. The group is a part of index to object. It means you don't need to worry the cost of seeking objects by group.(#1734 add group to all objects)
  - Topic is a complicated object having a bunch of configs, and now all available configs is exposed by broker APIs. This new feature is for advanced user who long to get everything under control. ( #1997 Enable BrokerCluster to show the available configs of topic)
  - In ohara, all objects need a stored data to make reusable. We need to apply this rule to all clusters in ohara. (#1544 Refactor cluster creation to two steps)

- Docs improvement
  - Document writing is now integrate with Jenkins build. You can see the fail message in PR page if Jenkins build **docs** fail.(#1884, #1988)
  - Convert format from markdown(md) to reStructuredText(rst) (#1840, #1987, #2095)
  - New docs: How to build Ohara docs(#1984)
  - New docs: A quick example for rst document writing(#2073)
----------------------------------------------------------
**ToDo**
- [x] Create 0.7 branch (base on last commit of frozen day)
- [x] Update version of master branch to 0.8.0-SNAPSHOT(skip path ohara/docs) #2255 
- [x] 設定 jenkins 使 0.7 和 0.8.0-SNAPSHOT 都可以 build code 和測試
- [x] Update document link to 0.7 branch #2255 
- [x] Remove unused (or unnecessary) functions from 0.7 branch (skip this step)
- [x] Meeting ohara product testing
- [x] Create ohara product testing report issue #2254 
- [x] Update version of 0.7 branch to 0.7.0 #2419
- [x] Upload Bintray repo
- [x] Add tags to release wiki page
- [x] Add change log to release wiki page
- [x] Add 0.7 binaries to github download
- [x] Update 0.7 branch's docs version to 0.7
- [x] Eliminate all 0.7.0-SNAPSHOT images from docker hub
- [x] Update version of 0.7 branch to 0.7.1-SNAPSHOT #2434 
- [x] Add the quick start vm to github download

**Comment by wu87988622** [comment]
/cc @vitojeng @chia7712 @saivirtue @eechih @konekoya 

Please help fill in the highlights.
Thanks everybody the support.

**Comment by jackyoh** [comment]
@wu87988622 漏掉 ping 我了

**Comment by konekoya** [comment]
@wu87988622 done :)

**Comment by vitojeng** [comment]
Remind: please fulfill the highlight instead of issue item list

**Comment by chia7712** [comment]
@wu87988622 please add a task to eliminate all 0.7.0-SNAPSHOT images from docker hub? They will be useless after you have released 0.7.0 images.

**Comment by wu87988622** [comment]
> please add a task to eliminate all 0.7.0-SNAPSHOT images from docker hub? They will be useless after you have released 0.7.0 images.

ok~ good point

**Comment by wu87988622** [comment]
@oharastream/developer
Please review me releases page thanks.
[releases](https://github.com/oharastream/ohara/releases)

**Comment by konekoya** [comment]
@wu87988622 updated manager's

**Comment by vitojeng** [comment]
Thanks @wu87988622 for driving this release. Well done!
