### ISSUE TITLE
Remove enzyme and migrate frontend unit tests to react-testing-library

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1873]
Since enzyme is buggy and react-testing-library is a better alternative 
https://reactjs.org/docs/test-utils.html#overview

- [x] Migration existing components
  - [x] Pipeline toolbar unit test (#1937)
  - [x] Add more tests to pipeline toolbar (#1981)
  - [x] Migrate pipeline new/edit page to use react testing library (#2081)
  - [x] Migrate pipeline list page to use react testing library (#2035)
- [x] Remove enzyme packages
  - [x] Remove enzyme from header component (#2007)
  -  [x] Remove all the enzyme unit tests from manager (#2040)
  - [x] Remove enzyme from HomePage.js and App.js (#2054)
- [x] Remove enzyme package and its settings from manager (#2109)
