### ISSUE TITLE
Redesign connector API's tags definition

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2049]
Tags are now part of the connector API definition. But needs a bit tweak so it can be properly rendered/ handled in the frontend

- [x] Supply a connector which contains all the valueType that's available to the connector author (@chia7712 ) (#2060)
- [x] Add a new valueType `TAGS` (@chia7712 ) (#2053)
- [x] Render valueType `TAGS` as an text field (#2225)
- [x] Add a tags definition in dumb source and sink connectors (#2224)
