### ISSUE TITLE
[Phase 1] Add unit tests to Material UI's components

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2107]
There are new common components that we are using which don't have unit test coverage yet. We should add necessary tests to make sure they're functioning well.

- [x] Dialog
    - [x] Add dialog component unit tests (#2128)
    - [x] Add delete dialog component unit tests (#2140)
- [x] Form
    - [x] Add button component unit tests (#2146)
    - [x] Add check box component unit tests (#2152)
    - [x] Add input field component unit tests (#2169)
    - [x] Add select component unit tests (#2190)

**Comment by konekoya** [comment]
@DavidMi-1 since the release date is on next Monday. I think we should close this issue on this Friday, so let's finish all the form tests (if possible) then, I will open another issue for you to add unit tests for the rest of components
