### ISSUE TITLE
[Phase 2] Add unit tests to Material UI's components

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2183]
Ref: #2107 

- [x] Add table and sort table components unit tests (#2253)
- [x] Add container, table loader and typography component unit tests (#2318)
- [x] Add progress bar unit tests (#2445)
- [x] Add workspace overview unit tests (#2508)

**Comment by konekoya** [comment]
@DavidMi-1 we'll be continuing the work of adding new unit tests to mui components in this issue
