### ISSUE TITLE
Fix pipeline stream app property form

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2209]
Follow #801, there's are many changes in the API. We should address them in this issue

- [x] Fix start and stop stream app from pipeline (backport to 0.7)
- [x] Fix start and stop stream app from pipeline (#2326)
- [x] Use metadata API to render stream app property form (0.7) (#2299)
- [x] Use metadata API to render stream app property form (0.8) (#2294)
