### ISSUE TITLE
[Phase 2] Migrate all the components to Mui

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2221]
Phase 2 of #1730 

- [x] [Manager] Use Mui's dialog component and remove react-modal (#2809)
  - [x] Update ohara version modal to use Mui's dialog (#2306) 
- [x] [Manager] Use snackbar to display notification (#2702)
- [x] [Manager] All Mui buttons should use uppercase letters (#2748)

**Comment by konekoya** [comment]
Form validation is a big issue and the logic will be changed according to #2470
