### ISSUE TITLE
Ohara 0.8.0 Release

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2278]
**Schedule**: Forzen: 10/1, Release: 10/9

## Highlights

<details>

**APIs:**

1. support setting fields for all clusters. (#2191 @saivirtue)
   - From now on, the parameters of a request from cluster API could be decided by users, all the parameters are moved to the "settings" field. You can use the API to create a cluster with your own custom settings.
1. config the services by what you want. (the available configs is exposed by definitions. see APIs). For example, you are able to config a topic with "flush.ms" to force the data to be frequently flush to disk. Or you can increase the segment size of a topic via setting "segment.bytes". Apart from *topic*, you are able to create *connector* and *streamapp* as you wish. (#2181)

**Connector:**
1. A powerful and flexible CSV connector (#2447 @eechih)
1. Introduce SMB Sink Connector (#2274 @eechih) 
1. Integration test support JDBC Source connector for the Oracle Database. (#1740  @jackyoh)
1. a simple but powerful restful services with json representation - JsonIn and JsonOut (#2547)

**Document**
1. A quick start tutorial document with a ready to use VM. (@vitojeng)
    - VM for quick start: Generate automatically and integrate with our Jenkins flow. (#2440)
    - Quick start: Use the quick start VM to demonstrate how to rapidly build data pipelines using Ohara.(#1787)

**UI:**
1. Allow users to upgrade an existing workspace (#1343) @wu87988622 
   - Add plugins tab in workspace and inside overview tab (#2482 )
   - Upgrade workspace with updated plugins (#2483)
   - Restore workspace if the upgrade failed (#2484)
1. Material UI migration phase 2 (#2221) (#2378) @konekoya @wu87988622 
1. Support all official connectors (#1969) @konekoya 
1. Support all value types (#2383) @konekoya 
1. JointJS survey (#866) @konekoya 
1. Topics can only be used in a single pipeline (#2469) @konekoya 
1. Adapt backend API changes (#2457) @konekoya 
----------------------------------------------------------
</details>

**ToDo:**
- [x] Create 0.8 branch (base on the last commit of frozen day)
- [x] Bump snapshot and docs versions (#2865)
- [x] Change branch and docs versions from 0.8 to 0.8.x (#2884)
- [x] Make sure jenkins is able to build and test on both 0.8.x and 0.9 branches
- [x] Deploy to demo environment
- [x] Create Ohara product testing report issue (#2869)
- [x] Update 0.8.x branch's SNAPSHOT version to 0.8.0 (#2976)
- [x] Create a new release draft in GitHub's release page
- [x] Build and Upload Ohara jars to Bintray repo
- [x] Add tag to release wiki page
- [x] Build and upload 0.8's binary files to the release draft we created earlier
- [x] Bump snapshot version to 0.8.1-SNAPSHOT (#3010)
- [x] Remove all 0.8.0-SNAPSHOT images from docker hub

**Comment by chia7712** [comment]
@wu87988622 @konekoya Is it possible to add "log" to our UI in 0.8?

**Comment by konekoya** [comment]
@chia7712 Are you talking about the API in #1532

**Comment by chia7712** [comment]
> Are you talking about the API in #1532

#1532 is a use case of log. The usage of logs for 0.8 are shown below.
1) show the logs of a starting workspace, 2) show the log of of streamapp

It seems to me the logs is a powerful information to say what happens on backend.

As a RM, I indeed long for this feature :)

**Comment by vitojeng** [comment]
If we want to add "log" to our UI, it would be better to create a simple proposal include a  wireframe.
/cc @eechih

**Comment by konekoya** [comment]
+1 with @vitojeng's suggestion.

As for this feature, I think we (frontend) already have quite some tasks at hand 😅 Maybe we can do this in 0.9. Sorry about that @chia7712!

**Comment by chia7712** [comment]
> Sorry about that

Not a problem at all. 

For another, what about definition for clusters?

**Comment by konekoya** [comment]
> For another, what about definition for clusters?

That's planned in 0.9 as well :)

**Comment by konekoya** [comment]
@oharastream/developer the frozen date of this release will be postponed. Since @vitojeng needs more time to discuss the ongoing product design in #2470 with us. I will update the description when the date is confirmed.

**Comment by konekoya** [comment]
@oharastream/developer updated the 0.8 codebase frozen and release date.

**Comment by konekoya** [comment]
@oharastream/developer Please remove 0.8 label (fix version) from your issues if the issue won't get into 0.8 release/branch. Thanks :)

**Comment by konekoya** [comment]
@oharastream/developer Hey guys! We will be releasing 0.8.0 in tomorrow afternoon. Just wanted to remind you if you haven't updated or wanted to add more about what you have done in this release in the __highlights__.

**Comment by konekoya** [comment]
## Highlights

- __Upgrade workspace__: You're now able to upgrade a running workspace with only a few keystrokes with our UI. This means you can upload/delete jars from your running workspace without stopping it and losing your data!

**Comment by konekoya** [comment]
@vitojeng Please help confirm the last task in the issue description, thanks :)

**Comment by konekoya** [comment]
0.8.0-SNAPSHOT images are removed, closing this issue
