### ISSUE TITLE
Stabilize manager's E2E test

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2301]
A handful of the E2E tests are failing very often now on CI (But we somehow cannot reproduce the failed tests on our locals)

- [x] Fix flaky test of __creates a workspace__ spec (#2301)
- [x] Delete zookeeper and broker that are added when creating a new workspace (#2301)
- [x] Delete the node when the test is done (#2301)
