### ISSUE TITLE
Support all the available settings definitions in manager

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2383]
A handful of definitions are still not supported in the frontend, so even if they exist in the API response. We won't display them in the UI

Ref: currently available definitions: 
https://ohara.readthedocs.io/en/latest/setting_definition.html?highlight=definitions#setting-definition-type

- [x] Add a default component for handling unknown value type (#2431)
- [x] Support long, double and short value types (#2524)
- [x] [Manager] Add Jar key and connector key support (#2383)

**Comment by konekoya** [comment]
cc @chia7712 @saivirtue @wu87988622

**Comment by chia7712** [comment]
> We won’t display them in the UI

Can we still display them as they are String type? Hiding them from UI obstructs user from assigning value manually.

**Comment by konekoya** [comment]
> Can we still display them as they are String type? Hiding them from UI obstructs user from assigning value manually.

Good point 👍  I will add a case to render a text input for unknown value types

**Comment by konekoya** [comment]
The rest of the tasks are tracked in #2749
