### ISSUE TITLE
Adapt new metadata api for all clusters

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2438]
#2243 has redefined the meanings of nodeNames - it is a "setting" from user input. Hence, the nodeNames should be moved to "settings". This change breaks the APIs compatibility.

- [x] Ohara Manager should fetch the object data from settings (@wu87988622 @konekoya) (#2684)
- [x] move nodeNames to settings for StreamClusterInfo (#2521)
- [x] move nodeNames to settings for ZookeeperClusterInfo (#2552 )
- [x] move nodeNames to settings for BrokerClusterInfo (#2575)
- [x] move nodeNames to settings for WorkerClusterInfo (#2516)
- [x] remove stale fields for StreamClusterInfo (#2739)
- [x] remove stale fields for ZookeeperClusterInfo (#2740)
- [x] remove stale fields for BrokerClusterInfo (#2755)
- [x] remove stale fields for WorkerClusterInfo (#2756)
- [x] update docs to remove stale fields for clusters

~This issue is blocked by #1736 since most clusters don't have "settings" field yet :(~
Done
