### ISSUE TITLE
A powerful and flexible CSV connector

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#2447]
as title

- [x] Support default definition in CSV source/sink connector #2319 
- [x] Refactor CSV source connector #2412 
- [x] Test base for CSV source connector #2595 
- [x] Test base for CSV sink connector # 2222
- [x] TextSourceTask#_poll make a hotspot on RowSourceContext #2038
