### ISSUE TITLE
Ohara 0.7.1 Release

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#2506]
## Hightlights

**hotfix:**

1.Ensure boolean value type is handled properly in manager #2501 
2.Perf connector config form not updating when switching between two Perf connectors #2526 
3.Upgrade manager's node.js version to 10.x #1047

**ToDo**
- [x] 設定 jenkins 使 0.7.1 和 0.8.0-SNAPSHOT 都可以 build code 和測試
- [x] Update version of 0.7 branch to 0.7.1 #2578 
- [x] Upload Bintray repo
- [x] Add tags to release wiki page
- [x] Add change log to release wiki page
- [x] Add 0.7.1 binaries to github download
- [x] Update 0.7 branch's docs version to 0.7.1
- [x] Eliminate all 0.7.1-SNAPSHOT images from docker hub
- [x] Update version of 0.7 branch to 0.7.2-SNAPSHOT
- [x] Add the quick start vm to github download

**Comment by chia7712** [comment]
@wu87988622 would you please highlight the hot fix for 0.7.1? thanks !

**Comment by wu87988622** [comment]
> @wu87988622 would you please highlight the hot fix for 0.7.1? thanks !

ok thanks you

**Comment by vitojeng** [comment]
@wu87988622 When do you expected this version to be released ?

**Comment by wu87988622** [comment]
> @wu87988622 When do you expected this version to be released ?

Wait until the error is fixed, in this week

**Comment by vitojeng** [comment]
Got it.
