### ISSUE TITLE
Apply group concept for all cluster

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2570]
Currently, we already live in a group world, this rule should apply to clusters.
After this issue, the actual container name format will be:
`{PREFIX_KEY}-{GROUP}-{CLUSTER_NAME}-{SERVICE}-{HASH}`

Both GROUP and CLUSTER_NAME length limit is 20 chars for now.

- [x] Apply group concept for zookeeper (#2583)
- [x] Apply group concept for broker (#2624)
- [x] Apply group concept for worker (#2629)
  - Remove stale method
- [x] Apply group concept for stream (#2602)
- [x] Refactor collie.creator infra to benefit the api.request (see [comment](https://github.com/oharastream/ohara/pull/2624#pullrequestreview-286617999)) (#2633)

**Comment by chia7712** [comment]
```scala
  private[this] def updateState[Cluster <: ClusterInfo: ClassTag](cluster: Cluster, metricsKey: Option[String])(
    implicit meterCache: MeterCache,
    collie: Collie[Cluster],
    executionContext: ExecutionContext): Future[Cluster] =
    collie
      .clusters()
      .map(
        _.keys
          .find(_.name == cluster.name)  // _.key == cluster.key
```
@saivirtue should we make above change in this issue?

**Comment by saivirtue** [comment]
>  should we make the above change in this issue?

We should :)
