### ISSUE TITLE
Ohara 0.8 product testing report

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2869]
## 測試項目

<details>
<summary><b>1. 基本測試:</b></summary>

- [ ] 確認畫面（UI）與設計稿（Design）是否一致
  - 顏色、字型、符號、圖片、...
- [ ] 檢查所有畫面的 Title 名稱是否正確
- [ ] 所有連結是否有前往正確頁面
- [ ] 切換視窗大小時，有無跑版情形
- [ ] 切換視窗大小後，文字與圖形是否竄行
- 表單
  - [ ] 任何一個必填欄位未填寫，不能送出
  - [ ] 表單送出中，應該明確表達正在處理中的訊號
  - [ ] 表單送出中，應該要凍結表單（除非有提供取消功能）
  - [ ] 任何表單至少要有 CTA 及 Cancel 兩類按紐 (CTA: Call-To-Action)
- 訊息
  - [ ] 成功訊息，應該要明確指出完成對象
  - [ ] 錯誤訊息，應該要明確指出錯誤對象
  - [ ] 確認訊息
    - [ ] 刪除確認，應該要明確指出欲刪除對象
- 按鈕
  - [ ] 任何一個刪除按鈕，都要有刪除確認提示
- 鼠標
  - [ ] 移動到所有可以點擊的元素，要出現 pointer cursor
      - Button, Link icon, Link text, ...
</details>

<details>
<summary><b>2.功能測試: </b></summary>

#### Note: 
  - Please make sure you're testing these cases on demo environment
  - The full test procedure can be found in each case's link
  - Add your test report in the comment

### Case 1: FTP to Topic to Streamapp to HDFS
[Full test procedure](https://github.com/oharastream/ohara/blob/master/docs/testcase/pipeline-ftp-topic-streamapp-hdfs.md)

- [ ] Create a new workspace with three nodes
- [ ] Create two topic and upload a stream app jar into the workspace
- [ ] Create a new pipeline, add some connectors, topics and a stream app
- [ ] 連接 FTP source -> Topic -> StreamApp -> Topic -> HDFS sink
- [ ] Prepare the required folders and test data on the FTP server
- [ ] Start all connectors and stream app
- [ ] Verify which test data was successfully dumped to HDFS

### Case 2: JDBC to Topic to FTP
[Full test procedure](https://github.com/oharastream/ohara/blob/master/docs/testcase/pipeline-jdbc-topic-ftp.md)

- [ ] Create a new workspace with three nodes
- [ ] Create new topic into the workspace
- [ ] Create a new pipeline, add a jdbc source connector, topics and a ftp sink connector
- [ ] 連接 JDBC source -> Topic -> FTP sink
- [ ] Prepare the required table and data on the PostgreSQL server
- [ ] Prepare the required output folder on the FTP server
- [ ] Start all connectors on the second_pipeline page
- [ ] Verify which test data was successfully dumped to FTP server

</details>

<details>
<summary><b>3. 安裝測試:</b></summary>

#### Note: 
  - Test this case in your own environment 
  - The full test procedure can be found in each case's link
  - Add your test report in the comment

### Case 1: Ohara installation
[Full test procedure](https://github.com/oharastream/ohara/blob/master/docs/testcase/ohara-installation.md)

- [ ] Confirm your use the hardware specification
- [ ] Confirm your use version
- [ ] Install Kubernetes
- [ ] Running the Ohara Configuration service
- [ ] Running the Ohara Manager service

</details>
### 設計稿：
- Upgrade workspace: #1364

### 測試環境：
- Ohara
  - Mode: k8s 
  - Version: 0.8.0-SNAPSHOT
  - Build date: 
- 測試工具
  - 瀏覽器：Chrome  76.0.3809.100 
  - 最小螢幕寬度：1200

### 功能測試：
- [x] #2894 [Manager] Don't start a topic if it's failed in the creation phase (__confirmed by__: @konekoya @DavidMi-1)
- [x] #2891 [Manager] Don't update a connector when it's running (__confirmed by__: @konekoya @DavidMi-1)
- [x] #2886 Remove column definition from JsonIn and JsonOut (__confirmed by__: @konekoya @DavidMi-1)
- [x] #2901 [Manager] Connector should display the node it contains instead of the node in workspace (__confirmed by__: @konekoya @DavidMi-1)
- [x] #2888 Topic APIs should prevent users from inputting negative number to partitions and replications (__confirmed by__: )
- [x] #2886 Remove column definition from JsonIn and JsonOut (__confirmed by__: @konekoya)
- [x] #2902 [Manager] Prevent UI from breaking when connector's column table has wrong inputs (__confirmed by__: @konekoya @DavidMi-1)
- [x] #2914 Fail to validate Ftp, hdfs and Rdb when the request carries the workerClusterKey
- [x] #2904  fix weird warnings "Check docer version" from k8s-pre-install.sh
- [x] #2828 Failed to parse container name in ssh mode when there are non-hosted containers
- [x] #2920 Validation APIs does not return error report when we define the incorrect rdb settings
- [x] #2917 the consumer used to receive validation reports is closed too early
- [x] #2924 [Manager] Don't create a graph if the new connector's name is already taken in the pipeline (__confirmed by__: @konekoya)
- [x] #2930 [Manager] The stream jars link is broken in workspace overview's stream jars section (__confirmed by__: @konekoya)
- [x] #2938 JsonIn should use java.BigDecimal rather than scala.BigDecimal
- [x] #2942 [Manager] Should handle topic starting error
- [x] #2943 [Manager] Disable column table when the connector is running
- [x] #2954 [Manager] Display connector running state without a page refresh
- [x] #2958 [Manager] Only display topics that are belong to the current workspace in overview page
- [x] #2964 Failed to get/list Connector/Topic if it count on a non-running cluster

**Comment by konekoya** [comment]
@chia7712 @DavidMi-1 @HarryChiang143 Please leave your test report in this issue.

**Comment by konekoya** [comment]
@chia7712 @DavidMi-1 @HarryChiang143 

Please start testing the [__ohara installation__](https://github.com/oharastream/ohara/blob/master/docs/testcase/ohara-installation.md) 

I'm going thur the normal test cases locally today and found out the docs need some updates/tweaks due to the UI changes from this release. So I will file a PR to update the test case docs today. You guys can start to test the installation case in the meantime. Let me know if you have any problems/questions regarding the tests.

**Comment by DavidMi-1** [comment]
## 測試項目
<details>
<summary><b>1. 基本測試:</b></summary>
* [ ]  確認畫面（UI）與設計稿（Design）是否一致
  
  * 顏色、字型、符號、圖片、...
* [ ]  檢查所有畫面的 Title 名稱是否正確
* [ ]  所有連結是否有前往正確頁面
* [ ]  切換視窗大小時，有無跑版情形
* [ ]  切換視窗大小後，文字與圖形是否竄行
* 表單
  
  * [ ]  任何一個必填欄位未填寫，不能送出
  * [ ]  表單送出中，應該明確表達正在處理中的訊號
  * [ ]  表單送出中，應該要凍結表單（除非有提供取消功能）
  * [ ]  任何表單至少要有 CTA 及 Cancel 兩類按紐 (CTA: Call-To-Action)
* 訊息
  
  * [ ]  成功訊息，應該要明確指出完成對象
  * [ ]  錯誤訊息，應該要明確指出錯誤對象
  * [ ]  確認訊息
    
    * [ ]  刪除確認，應該要明確指出欲刪除對象
* 按鈕
  
  * [ ]  任何一個刪除按鈕，都要有刪除確認提示
* 鼠標
  
  * [ ]  移動到所有可以點擊的元素，要出現 pointer cursor
    
    * Button, Link icon, Link text, ...
</details>
<details>
<summary><b>2.功能測試:</b></summary>
#### Note:
* Please make sure you're testing these cases on demo environment
* The full test procedure can be found in each case's link
* Add your test report in the comment

### Case 1: FTP to Topic to Streamapp to HDFS
[Full test procedure](https://github.com/oharastream/ohara/blob/master/docs/testcase/pipeline-ftp-topic-streamapp-hdfs.md)

* [ ]  Create a new workspace with three nodes
* [ ]  Create two topic and upload a stream app jar into the workspace
* [ ]  Create a new pipeline, add some connectors, topics and a stream app
* [ ]  連接 FTP source -> Topic -> StreamApp -> Topic -> HDFS sink
* [ ]  Prepare the required folders and test data on the FTP server
* [ ]  Start all connectors and stream app
* [ ]  Verify which test data was successfully dumped to HDFS

### Case 2: JDBC to Topic to FTP
[Full test procedure](https://github.com/oharastream/ohara/blob/master/docs/testcase/pipeline-jdbc-topic-ftp.md)

* [ ]  Create a new workspace with three nodes
* [ ]  Create new topic into the workspace
* [ ]  Create a new pipeline, add a jdbc source connector, topics and a ftp sink connector
* [ ]  連接 JDBC source -> Topic -> FTP sink
* [ ]  Prepare the required table and data on the PostgreSQL server
* [ ]  Prepare the required output folder on the FTP server
* [ ]  Start all connectors on the second_pipeline page
* [ ]  Verify which test data was successfully dumped to FTP server
</details>
<details>
<summary><b>3. 安裝測試: Done</b></summary>
### Case 1: Ohara installation
* [x]  Confirm your use the hardware specification
* [x]  Confirm your use version
* [x]  Install Kubernetes
* [x]  Running the Ohara Configuration service
* [x]  Running the Ohara Manager service
</details>

### 測試結果：
- 成功打開 Ohara manager 網頁如下圖
![image](https://user-images.githubusercontent.com/44669519/66106082-a03ff000-e5ef-11e9-9dc1-fc9cfbe07cec.png)

## 測試所發現的問題紀錄
### 設計稿：

### 測試環境：
* Ohara
  
  * Mode: k8s
  * Version: 0.9.0-SNAPSHOT
  * Build date: 2019-10-02 22:26:36
* 測試工具
  
  * 瀏覽器：Chrome  76.0.3809.100
  * 最小螢幕寬度：1200

### 基本測試：
### 功能測試：

**Comment by konekoya** [comment]
## 測試項目
<details>
<summary><b>1. 基本測試:</b></summary>

* [ ]  確認畫面（UI）與設計稿（Design）是否一致
  
  * 顏色、字型、符號、圖片、...
* [ ]  檢查所有畫面的 Title 名稱是否正確
* [ ]  所有連結是否有前往正確頁面
* [ ]  切換視窗大小時，有無跑版情形
* [ ]  切換視窗大小後，文字與圖形是否竄行
* 表單
  
  * [ ]  任何一個必填欄位未填寫，不能送出
  * [ ]  表單送出中，應該明確表達正在處理中的訊號
  * [ ]  表單送出中，應該要凍結表單（除非有提供取消功能）
  * [ ]  任何表單至少要有 CTA 及 Cancel 兩類按紐 (CTA: Call-To-Action)
* 訊息
  
  * [ ]  成功訊息，應該要明確指出完成對象
  * [ ]  錯誤訊息，應該要明確指出錯誤對象
  * [ ]  確認訊息
    
    * [ ]  刪除確認，應該要明確指出欲刪除對象
* 按鈕
  
  * [ ]  任何一個刪除按鈕，都要有刪除確認提示
* 鼠標
  
  * [ ]  移動到所有可以點擊的元素，要出現 pointer cursor
    
    * Button, Link icon, Link text, ...
</details>
<details>
<summary><b>2.功能測試:</b></summary>

#### Note:
* Please make sure you're testing these cases on demo environment
* The full test procedure can be found in each case's link
* Add your test report in the comment

### Case 1: FTP to Topic to Streamapp to HDFS
[Full test procedure](https://github.com/oharastream/ohara/blob/master/docs/testcase/pipeline-ftp-topic-streamapp-hdfs.md)

* [x]  Create a new workspace with three nodes
* [x]  Create two topic and upload a stream app jar into the workspace
* [x]  Create a new pipeline, add some connectors, topics and a stream app
* [x]  連接 FTP source -> Topic -> StreamApp -> Topic -> HDFS sink
* [x]  Prepare the required folders and test data on the FTP server
* [x]  Start all connectors and stream app
* [x]  Verify which test data was successfully dumped to HDFS

### Case 2: JDBC to Topic to FTP
[Full test procedure](https://github.com/oharastream/ohara/blob/master/docs/testcase/pipeline-jdbc-topic-ftp.md)

* [ ]  Create a new workspace with three nodes
* [ ]  Create new topic into the workspace
* [ ]  Create a new pipeline, add a jdbc source connector, topics and a ftp sink connector
* [ ]  連接 JDBC source -> Topic -> FTP sink
* [ ]  Prepare the required table and data on the PostgreSQL server
* [ ]  Prepare the required output folder on the FTP server
* [ ]  Start all connectors on the second_pipeline page
* [ ]  Verify which test data was successfully dumped to FTP server
</details>
<details>
<summary><b>3. 安裝測試: </b></summary>

### Case 1: Ohara installation
* [ ]  Confirm your use the hardware specification
* [ ]  Confirm your use version
* [ ]  Install Kubernetes
* [ ]  Running the Ohara Configuration service
* [ ]  Running the Ohara Manager service
</details>

### 測試結果：
- 成功打開 Ohara manager 網頁如下圖
![image](https://user-images.githubusercontent.com/44669519/66106082-a03ff000-e5ef-11e9-9dc1-fc9cfbe07cec.png)

## 測試所發現的問題紀錄
### 設計稿：

### 測試環境：
* Ohara
  
  * Mode: k8s
  * Version: 0.9.0-SNAPSHOT
  * Build date: 2019-10-02 22:26:36
* 測試工具
  
  * 瀏覽器：Chrome  76.0.3809.100
  * 最小螢幕寬度：1200

### 基本測試：
### 功能測試：

**Comment by chia7712** [comment]
![2019-10-03 17-35-58 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66115915-6200fb80-e604-11e9-89f2-64ddd14470df.png)

文字顯示不正確

Jmxport => JMX port
exporterport => exporter port

**Comment by chia7712** [comment]
![2019-10-03 17-41-31 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66116302-0d11b500-e605-11e9-9315-bad4ffd82134.png)

提示字不該使用"違法"的字"Kafka Topic"（大寫和空白不允許）

**Comment by chia7712** [comment]
![2019-10-03 17-44-50 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66116567-81e4ef00-e605-11e9-87cd-e204f3ce5763.png)

the "column" is useless to JsonIn ...

**Comment by chia7712** [comment]
![2019-10-03 18-07-23 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66118330-b017fe00-e608-11e9-9871-b17c36e950f7.png)

是否將存取不存在的資源重新導向統一的頁面？

**Comment by chia7712** [comment]
![2019-10-03 21-22-59 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66130401-43126180-e624-11e9-8086-4406110232a2.png)

不斷跳出錯誤說我在嘗試修改一個正在運行的connector ...

**Comment by chia7712** [comment]
@wu87988622 Is there a page to show the distribution of connectors? IIRC, you had demo the usage of JsonIn and JsonOut but I failed to fine out the distribution via our UI...

**Comment by chia7712** [comment]
![2019-10-03 21-32-47 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66131091-5d007400-e625-11e9-8186-04bff7de2dba.png)

我們必須有個說明說為什麼topic不能被選擇...或者是乾脆隱藏掉已經被用的topics...

**Comment by chia7712** [comment]
![2019-10-03 21-36-12 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66131463-0c3d4b00-e626-11e9-844a-ed2f29d83431.png)

we should prevent user from inputting negative number to topic ...

**Comment by konekoya** [comment]
> 我們必須有個說明說為什麼topic不能被選擇...或者是乾脆隱藏掉已經被用的topics...

I think we can add a little message to help user understand this. Completely removed them is a bit confused :)

**Comment by konekoya** [comment]
> BTW, 前端在建立(post and then start) topic後應該要檢查一下topic的狀態，如果此時topic建立失敗應該要有對應的錯誤訊息

I also noticed this yesterday. @wu87988622 I think we should fix this in 0.8. Would you mind submiting a PR?

**Comment by chia7712** [comment]
![2019-10-04 12-02-16 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66180246-d9836900-e69e-11e9-8cc6-33f61db54540.png)

重現步驟：

1. 使用ssh mode
1. 加入三個nodes
1. 啟動workspace
1. 建立一個topic
1. 建立一個pipeline
1. 加入一個topic
1. 加入PerfSource
1. 給PerfSource加入一個column（如下圖)

![2019-10-04 12-03-46 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66180294-0cc5f800-e69f-11e9-8368-f3b1521c826d.png)

**Comment by chia7712** [comment]
![2019-10-04 12-13-04 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66180724-b35ec880-e6a0-11e9-8687-acde22b50ed2.png)

@wu87988622 @konekoya  the enabled "value" is only "string". Is it caused by our weak definition? (related to #2900)

**Comment by wu87988622** [comment]
> @wu87988622 Is there a page to show the distribution of connectors? IIRC, you had demo the usage of JsonIn and JsonOut but I failed to fine out the distribution via our UI...

只要點擊相關得rest 右方 node 將會顯示他所部署的節點

**Comment by chia7712** [comment]
![2019-10-04 12-29-37 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66181251-aa6ef680-e6a2-11e9-9d41-a9bc5cd3a60c.png)

> 右方 node 將會顯示他所部署的節點

which one?

**Comment by wu87988622** [comment]
> ![2019-10-04 12-29-37 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66181251-aa6ef680-e6a2-11e9-9d41-a9bc5cd3a60c.png)
> 
> > 右方 node 將會顯示他所部署的節點
> 
> which one?

Node(ppp)

**Comment by chia7712** [comment]
> Node(ppp)

The connector is deployed on a node only so it should NOT show all nodes in this page

**Comment by konekoya** [comment]
> @wu87988622 @konekoya the enabled "value" is only "string". Is it caused by our weak definition? (related to #2900)

Yes, our definition doesn't have a field which describes supported types. The __string__ is currently hardcoded in the frontend ...

**Comment by wu87988622** [comment]
> > Node(ppp)
> 
> The connector is deployed on a node only so it should NOT show all nodes in this page

ok Thanks i will open issue backport 0.8

**Comment by HarryChiang143** [comment]
## 測試項目 

<details>
<summary><b>1. 基本測試</b></summary>
</details>

<details>
<summary><b>2. 功能測試: </summary>
</details>

<details>
<summary><b>3. 安裝測試: (Done)</b></summary>

Note:

- Test this case in your own environment
- The full test procedure can be found in each case's link
- Add your test report in the comment

### Case 1: Ohara installation

- [v] Confirm your use the hardware specification
- [v]  Confirm your use version
- [v]  Install Kubernetes
- [V]  Running the Ohara Configuration service
- [v]  Running the Ohara Manager service
</details>

## 安裝測試結果：

- 成功打開 Ohara manager 網頁如下圖
<img width="1429" alt="螢幕快照 2019-10-07 上午11 32 56" src="https://user-images.githubusercontent.com/46185836/66283763-5d379280-e8f7-11e9-8f18-60016decbbc9.png">



## 測試所發現的問題紀錄

### 設計稿：
- (設計稿 Issue Number 紀錄在此)

### 測試環境：
- Ohara
  - Mode: k8s
  - Version: 0.8.0-SNAPSHOT
  - Build date: 2019-10-07 02:11:35
- 測試工具
  - 瀏覽器：Chrome 版本 77.0.3865.90 (正式版本) (64 位元)
  - 最小螢幕寬度：1200

### 基本測試：
- (基本測試所發現的問題，紀錄在此)

### 功能測試：
- (功能測試所發現的問題，紀錄在此)

### 安裝測試：
- 關於安裝文件中使用root進行安裝的議題討論已另開議題討論
https://github.com/oharastream/ohara/issues/2926

**Comment by DavidMi-1** [comment]
* 在新增 topics 時 replication factor 如果設為零, topic 會建立失敗, 可是如果是 partition 設為零, topic 會建立成功 ( 附圖一); 在 pipeline 中有 connector 使用到這個 topic 的話, 就會啟動失敗, 顯示
' Error: topic:{"group":"xxx","name":"yyy"} is not running ' ( 附圖二), 附圖示如下：
圖一
![image](https://user-images.githubusercontent.com/44669519/66362478-89194d80-e9b5-11e9-886a-fba7a5840962.png)
圖二
![image](https://user-images.githubusercontent.com/44669519/66362480-8d456b00-e9b5-11e9-92c3-78670d468e7f.png)

**Comment by chia7712** [comment]
![2019-10-08 13-51-31 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66370414-c5a77200-e9d2-11e9-9a35-9b1a67fd836a.png)


It does not redirect to the page for nonexistent resource.

**Comment by chia7712** [comment]
在不同workspaces裡相同名字的topics無法被使用

重現步驟：
1. 建立兩個

**Comment by chia7712** [comment]
![2019-10-08 14-58-39 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66373842-2be4c280-e9dc-11e9-86da-856c7741c13d.png)
![2019-10-08 14-58-41 的螢幕擷圖](https://user-images.githubusercontent.com/6234750/66373843-2be4c280-e9dc-11e9-9c9b-9ca7cbc59174.png)

ghost topics!!! (the topic "t0" belongs to another workspace)

**Comment by konekoya** [comment]
Thanks for the help everyone! I'm closing this issue as we're about to release 0.8 today :)
