### ISSUE TITLE
Update test case docs

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2882]
Due to the UI changes, we should update the test cases :)

- [x] Update UI test case 1 (#2883)
- [x] Update UI test case 2 (#2903)
- [x] Update UI test case and installation docs (#2899)

**Comment by konekoya** [comment]
Hmm, I'm not sure if we should backport this to 0.8 since it's just a docs change?

@oharastream/developer

**Comment by saivirtue** [comment]
I'm ok with only change the master branch :)

**Comment by vitojeng** [comment]
> Hmm, I'm not sure if we should backport this to 0.8 since it's just a docs change?
> 
> @oharastream/developer

IMO, we only need update the master branch.
