### ISSUE TITLE
Replace deprecated APIs with the new ones

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#298]
Some configurator APIs are deprecated and would eventually be removed.

As this issue is a bit more complicated than we planned. I'm splitting this into
two PRs so it matches our PR [guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md#a-pull-request-should) :)

- [x]  #486 Update logs, pipeline, and work list page APIs
- [x] #488 Remove config modals
- [x] #489 Add test connection button in HDFS sink prop form

required by #427
