### ISSUE TITLE
[Manager] Scaffolding new frontend codebase

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2994]
- [x] Remove old UI components from manager (#3025)
- [x] Create Mui color theme for the new UI (#3039)
- [x] Update manager's development guideline (#3045)
- [x] Add Ohara brand and main navigation (#3066)
- [x] Add snackbar context into the new UI (#3078)
- [x] Add an E2E test case to guard against 404 page (#3085)
- [x] Display a workspace automatically if there's an existing one (#3096)
- [x] Create context APIs for accessing shared global data (I've created a few contexts in this issue, more context can be added if necessary)

 ### Things I don't know what/how to do yet:
- [x] Active state for workspace
- [x] Pick another icon for the event log

**Comment by konekoya** [comment]
@wu87988622 @saivirtue

**Comment by konekoya** [comment]
I'm thinking about completely ditching frontend unit test since:
1. It's hard to write and maintain these tests
2. We often spend MUCH more time in the unit tests rather than the actual feature...
3. E2E tests give us way more confidence than unit tests 
4. We tend to write tests that don't bring much value for us
