### ISSUE TITLE
Ohara 0.8.1 Release

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3007]
### Bug fixes
- [x] [Manager] Fix connector update issue (#2998)
- [x] the response entity doesn't release correctly (#3035)
- [x] [Manager] Fix test config button disabled state (#3051)

**ToDo:**
- [x] Update 0.8.x branch's SNAPSHOT version to 0.8.1 (#3055)
- [x] Deploy to demo environment
- [x] Create a new release draft in GitHub's release page
- [x] Build and Upload Ohara jars to Bintray repo
- [x] Add tag to release wiki page
- [x] Build and upload 0.8's binary files to the release draft we created earlier
- [x] Remove all 0.8.1-SNAPSHOT images from docker hub
- [x] Bump 0.8.x branch's snapshot version to 0.8.2-SNAPSHOT

**Comment by chia7712** [comment]
Are there critical bugs? If so, please add the issue links.

**Comment by konekoya** [comment]
Right on it :)

**Comment by konekoya** [comment]
@vitojeng Could you help remove these 0.8.1-SNAPSHOT images on our doucker hub, thanks!
