### ISSUE TITLE
Ohara 0.9.0 Release

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3019]
**Schedule**: ~Forzen: 2020/1/5, Release: 2020/02/17~

Forzen: 2020/02/17 (一), Release: 2020/03/20 (五)

### Need To Be Done
<details>

**[Manager]**
- [x] Disable the following functions (#3689) @konekoya 
  - Expert mode link
  - Event Log icon button
  - `add node` and `delete` buttons of node list & node view page in k8s mode
  - `Overview` and `Settings` tabs of workspace
  - More action icon button of edit workspace dialog
  - `Used by pipelines` column from edit workspace's topic list. And in workspace list dialog
- [x] upload file action of workspace should switch to the file tab after successfully uploading a file (#3698)  @konekoya 
- [x] workspace title should use the current workspace name (#3689) @konekoya 
- [x] add pipeline should delay the checking of naming rule (length > 1) (#3698) @konekoya 
- [x] add link lines to components of pipeline will cause weird display sometimes @wu87988622 #3649 
- [x] workspace last modified time is wrong in workspace list icon button (#3698) @konekoya 

**[Backend]**
- Ohara docs
  - [ ] Update restful api docs (@jackyoh, @chia7712)
  - [ ] Update Ohara Manager related pages (@konekoya)
- Quickstart VM docs
  - [ ] Quickstart VM docs (@konekoya)
</details>

## Highlights
<details><summary>Some important changes</summary>

### UI
1. Frontend project scaffolding (#2994)
1. Implement pipeline navigator (#3097)
1. Implement pipeline toolbar (#3331)
1. Implement pipeline toolbox (#3184)

### Tasks that have been moved to v0.10
1. Cluster settings
1. Event log
1. Navigator outline and filter
1. Property view
1. Passing timezone to UI by inspect APIs
1. add a `finish` step in creating workspace
1. Metrics of topic list change to 2/3 of overall layout

### APIs
1. LIST request accept filter queries now. For example, pass ```topics?a=b``` to get topics having setting "a -> b".
1. Log APIs is able to fetch Configurator service log
1. Info APIs is able  to fetch the available settings from the docker image which you are going to deploy
1. Query APIs is able to fetch the content of file and Topic
1. strict checks of resources dependencies. 
#### Zookeeper: 
1. CAN'T stop a zookeeper cluster used by RUNNING broker cluster.
1. CAN'T delete a zookeeper cluster refereed by broker cluster
#### Broker: 
1. CAN'T create a broker cluster related to nonexistent zookeeper cluster.
1. CAN'T stop a broker cluster used by RUNNING worker cluster, streamApp or topic.
1. CAN'T delete a broker cluster refereed by worker cluster, streamApp or topic
#### Worker: 
1. CAN'T create a worker cluster related to nonexistent broker cluster.
1. CAN'T create a worker cluster related to nonexistent jar
1. CAN'T stop a worker cluster used by RUNNING connector.
1. CAN'T delete a worker cluster refereed by connector
#### Topic:
1. CAN'T create a topic related to nonexistent broker cluster.
1. CAN'T stop a topic used by RUNNING connector or streamApp.
1. CAN'T delete a topic refereed by connector or streamApp
#### Connector:
1. CAN'T create a connector related to nonexistent worker cluster.
1. CAN'T create a connector related to topics which are not on same broker cluster
#### Stream:
1. CAN'T create a streamApp related to topics which are not on same broker cluster
1. CAN'T create a worker cluster related to nonexistent jar
#### File:
1. CAN'T delete a file used by Worker cluster or streamApp
#### Node:
1. CAN'T delete a node used by Worker, streamApp, Zookeeper or Broker

</details>

## ToDo

1. - [x] fork 0.9.x branch
1. - [x] change 0.9.0-SNAPSHOT to 0.10.0-SNAPSHOT for master branch (#4052)
1. - [x] Create a new testcase "jdbc->topic->stream->topic->hdfs" (#3695)
1. - [x] Create Ohara product testing report issue 
1. - [x] Make sure jenkins is able to build and test on both 0.9.x and 1.0 branches
1. - [x] change 0.9.0-SNAPSHOT to 0.9.0 for 0.9.x branch (#4370)
1. - [x] change "branch" to 0.9.0 for gradle.properties (#4387)
1. - [x] change "branch" to 0.9.x for build.yml (#4402)
1. - [x] Build and Upload Ohara jars to Bintray repo
1. - [x] Build and Upload docker images to dockerhub
1. - [x] Remove all 0.9.0-SNAPSHOT images from docker hub
1. - [x] Create release page
1. - [x] Deploy to demo environment (QA env is unavailable now so I skip this)

**noted: the above changes (5, 6, 7) should be completed by single PR in the future!!!**

**Comment by saivirtue** [comment]
ping @chia7712 
Feel free to take over this issue :)

**Comment by chia7712** [comment]
> Feel free to take over this issue :)

together :)

**Comment by chia7712** [comment]
@oharastream/developer 

I will start the release of 0.9.0 if #4313 is merged. Feel free to raise objection :)

**Comment by konekoya** [comment]
> I will start the release of 0.9.0 if #4313 is merged. Feel free to raise objection :)

#4313 is ready for 0.9. But 0.10's PR breaks some e2e tests due to the recent Manager's refactoring and structure changes. Should I just remove 0.10 from its task and so we can close the issue and ready for release?

**Comment by vitojeng** [comment]
@chia7712 Just raise #4332 , it would be better backport to 0.9.x

**Comment by chia7712** [comment]
> Should I just remove 0.10 from its task and so we can close the issue and ready for release?

The fix ought to be in both 0.9.0 and 0.10.0 if it is a "bug" fix :)

**Comment by chia7712** [comment]
I'm going to update the version to 0.9.0 if all tests pass again :)

**Comment by chia7712** [comment]
@oharastream/frontend Do you resolve the version issue? IIRC, you encountered that Ohara Manager fails to get the version file from the distribution files?

**Comment by konekoya** [comment]
> @oharastream/frontend Do you resolve the version issue? IIRC, you encountered that Ohara Manager fails to get the version file from the distribution files?

It was resolved by @saivirtue but we didn't plan backporting to 0.9.

**Comment by chia7712** [comment]
blocked by #4350
