### ISSUE TITLE
Introduce Shabondi: a http proxy service let user push data into Ohara

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#3022]
follow-up #160

Todo items
- [x] Shabondi WebServer(#3141)
- [x] Shabondi SourceRoutes(#3087)
- [x] Shabondi SinkRoutes(#3378)
- [x] Integrate with Configurator(#3591)
- [x] Integrate with Configurator, part 2(#4046) 
- [x] Shabondi Restful API docs(#951)
- [x] Improve Shabondi testing(#4559)

**Comment by vitojeng** [comment]
@oharastream/backend 
I would like to discuss the high level architecture concept and constrain about Shabondi.
The draft as follows: 
* Every Pipeline only allow to add **one** Shabondi source component and **one** Shabondi sink component.
* The Shabondi component(source or sink) in the Pipeline, contains multiple **passages**. 
* Every **passage** can be defined a url path, a destination(or source) topic, and schema.
* The Shabondi component(source or sink) in the Pipeline may running as multi-instance, just like StreamApp.(For early adaption, maybe only have one instance)

**Comment by chia7712** [comment]
> Every Pipeline only allow to add one Shabondi source component and one Shabondi sink component. So each pipeline uses up to two ports.

why? 

> Every passage can be defined a url path, a destination(or source) topic, and schema. Every data through passage is the same schema.

Since the URL count on "hostname", it implies each instance of shabondi host different (topic, schema)? It is a bit weird to me since the schema should be related to "topic" or "shabondi source/sink" rather than "instance" of shabondi.

**Comment by vitojeng** [comment]
> Since the URL count on "hostname", it implies each instance of shabondi host different (topic, schema)?

No. Hope the following example can be better explained.
For example, if we have a Shabondi source component in pipeline, only one instance. 
The node name is **k8s-node5** and the port is **32832**.
There have three passages defined in the source component, the three passages of url will be:
* http://k8s-node5:32832/{passage_1}/
* http://k8s-node5:32832/{passage_2}/
* http://k8s-node5:32832/{passage_3}/

Each passage is one input and one output, and have itself topic and schema, just like settings in the Ftp Source Connector.

**Comment by vitojeng** [comment]
The original idea is that one Shabondi component can handle mutiple passages.

After some discussion in the daily meeting, it seems one component handle one passage is more reasonable.

**Comment by chia7712** [comment]
> After some discussion in the daily meeting, it seems one component handle one passage is more reasonable.

If so, does one shabondi accept only one topic/schema?

**Comment by vitojeng** [comment]
Yep
-- 


---
Vito

**Comment by chia7712** [comment]
> Yep --

> Every Pipeline only allow to add one Shabondi source component and one Shabondi sink component. So each pipeline uses up to two ports.

I guess we have to allow user to deploy multiple shabondi so as to take different topics/schemas, right?

**Comment by vitojeng** [comment]
Yep. 

Let me update here:

* Shabondi have two types of component for Pipeline, one is **source** and another is **sink**
  * Source component allows the user to push data into a topic through HTTP request.
  * Sink component allows the user to pull data from a topic through HTTP request.
* Both Source component and Sink component contain settings such as **port**, **topic**, **schema**.
* Each pipeline allow to deploy multiple Shabondi source componet and sink component.
