### ISSUE TITLE
Add integrate automated tests with CI (QA)

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3028]
- API test
  - [x] Add node API tests (#3049)
  - [x] Add file API tests (#3061)
  - [x] Add broker, worker, zookeeper API tests (#3133)
  - [x] Add log, topic, validate API tests(#3149)
  - [x] Add connector, pipeline API tests (#3179)
  - [x] Add stream API tests (#3185)
-  e2e test

- Common tasks
  - [x] Save API tests video in another directory (move to issue #2659)
  - [x] Refactor api tests after #3121 @saivirtue

**Comment by chia7712** [comment]
feel free to ping me if you encounter gradle or jenkins error :)
