### ISSUE TITLE
[Manager] Implement pipeline navigator

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3097]
Some API related logic should be handled in #2995, I will leave some TODOs in this PR

- [x] Add pipeline navigator UI (#3106)
- [x] Add validation logic for new pipeline form (#3119)
- [x] Add pipeline route logic (#3126)
- [x] Open a dialog to create new workspace when there is no workspace (#3132)
