### ISSUE TITLE
[Manager] Create E2E tests for the new UI

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3161]
- [x] Add tests to verify devTool dialog works well (@saivirtue) (#3868)
- [x] Add a test to verify toolbox of pipeline can be worked normally (#3960)
- Add tests to verify pipeline can be worked normally
  - [x] Add a test to verify links of connector and topic can be worked normally (#4033)
  ~~- [ ] Add a test to verify links of stream, connector and topic can be worked normally (#4045)~~
  ~~- [ ] Add a test to verify auto add topic can be worked normally~~
  ~~- [ ] Add tests to verify settings and actions can be worked normally~~
- [x] Add a test to verify all routes are working as expected (#3891)
- [x] Add a test to verify a workspace can be created via quick mode (#3935)
- [x] Add a test to verify the node dialog (#3942)
- [x] Add a test to verify the topic dialog (#3976)
- [x] Add a test to verify the files dialog (#3981)
- [x] Add a test to verify the eventLog dialog (@saivirtue ) (#4042)
- [x] Bumping cypress to the newest version (#3936)

Additional tests:
~~- [ ] Add a test to verify select cells could link to the correct position of DevTool dialog~~

**Comment by saivirtue** [comment]
@konekoya 
I have pushed the in-progress commit of the first task into my repo (saivirtue/fix_3161_1)
feel free to pull it :)

**Comment by konekoya** [comment]
@saivirtue would you mind adding a task for bumping cypress version to the newest version?

**Comment by saivirtue** [comment]
> @saivirtue would you mind adding a task for bumping cypress version to the newest version?

Sure thing :)

**Comment by konekoya** [comment]
> Sure thing :)

Thanks :)

**Comment by saivirtue** [comment]
/cc @eechih 
Could you help me to accomplish the eventLog testing part?

**Comment by eechih** [comment]
> Could you help me to accomplish the eventLog testing part?

Sure
