### ISSUE TITLE
[Manager] Create developer dialog

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3181]
- [x] Implement the topic tab of Developer dialog layout and logic (#3260)
~- [ ] tunning topic tab css style~
- [x] Implement the log tab of Developer dialog layout and logic (#3344)
- [x] implement the log "sinceSeconds" logic (#3382)
