### ISSUE TITLE
[Manager] Implement pipeline toolbox

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3184]
- [x] Create basic toolbox UI (#3186)
- [x] Refactor and add the ability to toggle the toolbox (#3195)
- [x] Load list data into the toolbox (#3204)
- [x] Use the correct button component for toolbar (#3218)
- [x] Refactor and wire up basic pipeline graph (#3233)
- [x] Add the ability to drag and drop a component (#3259)
- [x] Reset pipeline states when switching between different pipelines (#3300)
- [x] Tweak add connector dialog when drag and drop from Toolbox (#3306)
- [x] Enable searching in the toolbox (#3330)

**Comment by konekoya** [comment]
@wu87988622
