### ISSUE TITLE
[Manager] Implement pipeline toolbar

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3331]
- [x] Create Toolbar layout and add necessary components (#3379)
- [x] Implement zoom in/out and fit feature (#3397)
- [x] Fix fit to content feature in Toolbar (#3415)
- [x] Fix various paper scale related bugs (#3433)
- [x] Implement centering a graph feature (#3450)
- [x] Refactor paper zooming function (#3484)
- [x] Fix group issue in pipeline (#3657)
- [x] Implement pipeline start/delete/remove actions (#3634)
- [x] Wire up metrics toggle button API (#3673)
- ~[ ] Implement pipeline actions API~ move to #3609
