### ISSUE TITLE
[Manager] Implement nodes page for edit workspace

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#3446]
- [x] Implement the node card (#3513 )
- [x] Switch the services (zookeeper, broker, worker)  (#3513 )
- [x] Persist the changed data  (#3513 )
- [x] Discard the changed data  (#3513 )
- [x] Display the count of change  (#3513 )

**Comment by eechih** [comment]
duplicated by #3513
