### ISSUE TITLE
[Manager] Wire up paper cell connection logic

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3485]
- [x] Tweak pipeline paper configurations and cell styles (#3488)
- [x] Apply each connector's connection logic (#3500)
- [x] Add hover and active state to links (#3527)
- [x] Add a new private topic when two connectors are connected (#3553)
- [x] Refactor Pipeline graph and toolbox (#3562)
