### ISSUE TITLE
[Manager] Redesign pipeline source code structure

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3809]
The currently pipeline UI has a serious issue. For instance, when a user drags and drops a new topic from Toolbox to Paper, since this action involves lots of API requests behind the scene. Our UI is trying to ensure that each step is success by "waiting" the request responses from the backend API. After that, the next step is then granted and can be continued. But this behavior "blocks" our user from continuing interacting with the rest of UI (meaning, users need to wait for the action to "complete" then can resume to do some other interactions)

#### This blocking behavior is making our UI:
- Hard to use, since you have to wait for many actions 🙅‍♂ 
- Creating a feel that our UI is extremely slow 🐢 
- We're less proud of our new UI 😉 

Fortunately, @eechih has come up with a better design which allows our UI to "not blocking" user interactions while API requests are going on in the background.

#### The design
The design basically just renders the UI that's needed right on the screen, but the API requests will still be running asynchronously behind each action, the flow will be looking a lot like the following:

<--- Initialize the paper (with data coming from backend API)
---- Create a new topic, it will be added right into the paper and the state is set to pending 
< ---- Make a request to backend API for creating a new topic and update pipeline endpoints (could be multiple requests)
----> If it's success, update the topic state to running, if it's failed, remove the topic from paper and update the pipeline to remove the topic from endpoints

From the above example, we try not to block the user action but rather to allow them running in the background and assuming the action is success. In the meantime, users can still interacting with our UI for most tasks and if the action is failed at some point, we will do a rollback and delete the topic that just created/added

#### Refactor of the current codebase
@eechih also proposes that we change our paper to be a dumb component which only renders by props and exposing needed event handlers and functions that allow other components to use. This also helps separating the API and paper actions (powered by JointJS).

Some of the public APIs that we can think of right now :)

##### Paper 
![Paper public APIs](https://www.dropbox.com/s/1f4zefl2yuaowkm/paper-api.jpg?raw=1)

##### Toolbox
![Toolbox public APIs](https://www.dropbox.com/s/jl7amnqkvu8ocfu/toolbox-api.jpg?raw=1)

#### Todos
- [x] Add necessary APIs for Paper to consume #3812
- [x] Redesign Paper component #3813
- [ ] ~~Redesign Toolbox component~~ (couldn't complete in 0.9.0)

**Comment by konekoya** [comment]
Big thank and kudo to @eechih 

/cc @saivirtue @wu87988622

**Comment by konekoya** [comment]
Update: We will move `onElementAdd` from Toolbox component to Paper itself since this makes our this add event can be reused from all components
