### ISSUE TITLE
Add necessary APIs for Paper to consume

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#3812]
- [x] Initialize paper data with pipeline api and check all cells (connector, topic, stream) #3961
- [x] Paper Connector action with Connector api (create, start, stop, remove, update) #3853 
- [x] Paper Topic and Stream action with Topic api and Stream api (create, start, stop, remove, update) #3883 
- [x] Paper disconnect action #3890 
- [x] Paper config action with Connector and Stream api #3915 
- [x] Paper onChange action with Pipeline API #3939 
- [x] Paper Metrics update with pipeline API #3974
