### ISSUE TITLE
[Manager] Redesign paper component

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3813]
Ref #3809 

- [x] Refactor pipeline components and expose basic public APIs (#3821)
- [x] Enable link related logic in Paper (#3840)
- [x] Refactor config dialog to adapt new Paper APIs (#3863)
- [x] Add onChange method in Paper (#3885)
- [x] Allow Paper's getCell method to search a cell by its name (#3894)
- [x] Change topic icon color when its status changed (#3900)
- [x] Add metrics related methods in Paper (#3912)
- [x] Add a highlight method in Paper (#3928)
- [x] Tweak onChange sub event types (#3926)
- [x] Refactor element structure and fix metrics scaling issue (#3955)
- [x] Add an onLoad method in Paper for loading data from backend (#3958)
- [x] Disable action buttons when a Paper element is in the pending state (#3959)
- [x] Fix Paper elements status not persistent after a page refresh issue (#3965)
- [x] Refactor Paper for adapting better element event handler binding structure (#3971)
- [x] Reset pipeline state when switching between different pipelines (0.10 #4072 ,0.9 #4084)
