### ISSUE TITLE
[Manager] Implement the EventLog page

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#3816]
- Implement the context api
  - [x] fetch event logs
  - [x] create a new event log (#3839 )
  - [x] clear event logs (#3839 )
  - [x] get the content of a log (#3844 )
- [x] Keep data in browser's LocalStorage or IndexedDB (#3839 )
- Implement the UI
  - [x] The event logs list (#3839 )
  - [x] The log content page (#3844 )
- [x] Event logs settings (#3854 )
- [x] Filter event logs (#3844 )
- Apply event log to context api (#3856 )

**Comment by saivirtue** [comment]
Thanks @eechih !
