### ISSUE TITLE
 Integrate Shabondi with Configurator, part 2

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4046]
required by #3022 
follow up #3591 

Todo itmes:
- [x] Split boot class and definitions into two groups: source and sink(#4057)
- [x] Shabondi minor refactor(#4475)
- [x] Add shabondi info to InspectAPI
  - [x] Add shabondi info(#4461)
  - [x] Add running shabondi info(#4494) 
- [x] Dependency check of Shabondi with Broker and Topic(#4501)
- [x] Enable Shabondi JMX port and HEAP_OPTS(#4511)
- [x] Enable shabondi metrics
  - [x] Enable shabondi metrics(#4536)
  - [x] Enable shabondi metrics in configurator route(#4547)
- [ ] ~Add more testing~ (Move to #4559)
