### ISSUE TITLE
[Manager] Create E2E tests for the new UI - Phase II

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4049]
This is the follow-up of #3161 
- [x] Add a test to verify links of stream, connector and topic can be worked normally (#4045)
- [x] Add a test to verify auto-add topic can be worked normally (#4065)
- [x] Add missing e2e tests (#4338)
  - devTool, eventLog

**Pipeline Related** (move to #5096)
- [x] ~~Add a test to verify settings and actions can be worked normally~~
- [x] ~~Add a test to verify select cells could link to the correct position of DevTool dialog~~
- [x] ~~Add a test to verify property view of elements in pipeline works normally~~
- [x] ~~Pipeline can be properly started and stopped via the action menu on Toolbar~~
- [x] ~~Pipeline can be completely removed via the action on Toolbar~~
- [x] ~~A shared topic can only be added into the same pipeline once~~
- [x] ~~Pipeline-topics have the correct naming logic (T(n))~~
- [x] ~~Ensure Paper elements' action buttons are disabled in different status~~

**Workspace Related** (move to #5096)
- [x] ~~Add tests to verify delete workspace works normally~~

- [x] ~~Reviewed skipped e2e tests~~ (move to #5096)
