### ISSUE TITLE
Refactor Performance 測試程式

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4053]
- [x] Performance 測試程式產生資料要有固定的大小 issue #3938
- [x] Performance 測試程式需要計算原始資料量大小 issue #4015 
- [x] Perforamcne 測試程式在 setup 資料要有時間設定 issue #4016
