### ISSUE TITLE
身為使用者，我希望能修改 custom connector 各種參數

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#419]
### Criteria
- [x] 基本參數：name, version, revision, author, description (#480)
- [x] 其他客製化參數，例如：data_dir, ...  (#480)
- [x] 參數要區分：readonly, editable  (#480)
- [x] 點選 pipeline 上的 graph，顯示 custom connector 表單
- [x] 讀取 meta data，動態顯示各種參數的欄位
- [x] 當狀態為啟動中，不可編輯任何參數
- [x] 修改參數後，自動儲存

**Comment by chia7712** [comment]
@eechih @konekoya Could we close this issue?

**Comment by eechih** [comment]
All related tasks are finished, change this story to review
ping @vitojeng
