### ISSUE TITLE
Roadmap of Ohara v1.0

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4213]
Ohara v1.0 was born if we complete all of the following tasks.

### Backend
* v0.10
  - [ ] Enable Persistence: Zookeeper & Broker
  - [ ] Connector support exactly once: all Ohara connectors
  - [ ] Enable Shabondi
* v0.11
  - [ ] Introduce universal runnable service
  - [ ] Introduce Websocket in Configurator
* v0.12
  - [ ] Leverage serialization tool
  - [ ] Enable Java 11 runtime support
  - [ ] Scalable Broker & Worker & Stream & Connector & Shabondi
  - [ ] Stream enhancement(api & exactly-once)

### Frontend
* v0.10
  - [ ] Workspace settings & restart
  - [ ] API refactor
  - [ ] Design wireframe of Persistence
* v0.11
  - [ ] Create workspace "Expert mode"
  - [ ] Introduce Websocket in node.js
  - [ ] Enable persistence settings
  - [ ] Design wireframe
    * Universal runnable service
    * Serialization
    * New layout design
* v0.12
  - [ ] Enable universal runnable service
  - [ ] Enable serialization

### Document: 
* v0.11
  - [ ] New structure of document
* v0.12
  - TBD

Any feedback about task items and schedule is welcome.
