### ISSUE TITLE
Ohara 0.10.0 Release

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4382]
## 1. Schedule
🚴‍♂️  Start 2020/03/16 (Mon.) 
❄️  Frozen: 2020/04/30 (Thu.) 
🐞  Testing & Fix bug: 2020/05/04 (Mon.) ~ 2020/05/27 (Wed.) 
🎉  Release: 2020/05/28 (Thu.) 

### Backend

1. - [x] Enable Ohara Volumn: Zookeeper & Broker (#4460)(70%)
1. - [x] Connector support exactly once: all Ohara connectors (#4457)(80%)
1. - [x] Enable Shabondi(#3022)(100%)
1. - [x] Upgrade kafka from 2.4.1 to 2.5.0 (#4569)
1. - [x] Upgrade gradle from 5.6.4 to 6.3.0 (#4491)
1. - [x] Upgrade Scala 2.12.11 to 2.13.1 (#4630)

### Frontend
- [x] API refactor
- [x] Introduce Redux to manage the state of application
- [x] Design - Ohara 0.10.0 mockup (#4498)
- [x] Introduce RxJS that makes it easier to compose asynchronous or callback-based code (#4456 )
- [x] Workspace settings & restart(90%)
    * Restart all services: zookeeper, broker, worker(data loss)
    * Rollback when restart workspace failed
    * Display progress log
- [x] Delete workspace
- [x] Design wireframe: Shared / plugin Jar

> Ohara 0.10.0 UI Tasks(#4521)

### UI
- Introduce **TypeScript** to rewrite API
- Introduce **Redux** to manage the state of application
- Introduce **RxJS** that makes it easier to compose asynchronous or callback-based code (#4456 )
- Configure workspace settings
- Restart and delete workspace

### Backend
- Enable Ohara Volumn: Zookeeper & Broker (#4460)
- Connector support exactly once: all Ohara connectors (#4457)
- Introduce Shabondi: a http proxy service let user push data into Ohara(#3022)
- Upgrade kafka from 2.4.1 to 2.5.0 (#4569)
- Upgrade gradle from 5.6.4 to 6.3.0 (#4491)
- Upgrade Scala 2.12.11 to 2.13.1 (#4630)
- Compatible to Java 11

##  4. ToDo
- [x] fork 0.10.x branch
- [x] Make sure jenkins is able to build and test on both 0.10.x and 0.11.x branches
- [x] change 0.10.0-SNAPSHOT to 0.11.0-SNAPSHOT for master branch
- [x] Deploy to demo environment
- [x] Create Ohara product testing report issue (#4539)
- [x] Create a new release draft in GitHub's release page
- [x] change 0.10.0-SNAPSHOT to 0.10.0 for 0.10.x branch
- [x] Build and Upload Ohara jars to Bintray repo
- [x] Add tag to release wiki page
- [x] Build and upload 0.10's binary files to the release draft we created earlier
- [x] Remove all 0.10.0-SNAPSHOT images from docker hub

**Comment by eechih** [comment]
@oharastream/developer Please highlight the main functions and features of this release. You can add a comment or modify the description.
