### ISSUE TITLE
[Manager] Migrate context API to Redux + RxJS architecture

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4456]
- [x] [Manager] Refactor files API to use the new architecture (#4412)
- [x] [Manager] Refactor streams API to use the new architecture (#4428)
- [x] [Manager] Refactor connector API to use the new architecture (#4452)
- [x] Encapsulate Axios as observers that rxjs can use (#4438)
- [x] [Manager] Migrate DevToolDialog to redux with rxjs (#4499)
- [x] [Manager] Migrate EventDialog to redux with rxjs (#4430)
- [x] [Manager] Migrate topic to redux with rxjs (#4467)
- [x] [Manager] Migrate snackbar to redux with rxjs (#4477)
- [x] [Manager] Use redux to refact the worker, broker and zookeeper context (#4347) - Harry
- [x] [Manager] Refactor files API and to include the error handling logic (#4504)
- [x] [Manager] Add an epic which handles the delete of pipeline itself and the services running on it (#4513)
- [x] [Manager] Make sure the pipeline all function is normal (#4512 ) -RobertYe
~~- [ ] [Manager] Update pipelinePropertyDialog at Final form to Redux form~~

**Comment by konekoya** [comment]
👋 Frontenders, could you add your migration tasks in the description? Even if it's finished. Many thanks!

**Comment by chia7712** [comment]
@konekoya thanks for this ticker :)

**Comment by konekoya** [comment]
@chia7712 @eechih I've removed the tasks from the list as all definitions seem to have its default value now :)

**Comment by konekoya** [comment]
@wu87988622 Please move redux-form task to another issue and close this issue when you've done so. Thanks 🙏

**Comment by wu87988622** [comment]
- [ ] [Manager] Update pipelinePropertyDialog at Final form to Redux form move to  #4700
