### ISSUE TITLE
[Manager] Writing tests for redux epic

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4508]
It's important to make sure our epics logic could be run as expected:
- [x] writing tests for appEpics (#4517)
- [x] writing tests for brokerEpics (#4537)
- [x] writing tests for devToolEpics (#4551)
- [x] writing tests for connectorEpics (#4649)
- [x] writing tests for eventLogEpics (#4542)
- [x] writing tests for fileEpics (#4601)
- [x] writing tests for nodeEpics (#4595)
- [x] writing tests for streamEpics (#4666)
- [x] writing tests for pipelineEpics (#4704)
- [x] writing tests for snackbarEpics (#4591)
- [x] writing tests for topicEpics (#4655)
- [x] writing tests for workerEpics (#4544)
- [x] writing tests for workspaceEpics (#4577)
- [x] writing tests for zookeeperEpics (#4543)
- [x] re-enable deleteWorkspaceEpic (#4679)
- [x] trigger event log for all epics when throwing exception (#4698)
