### ISSUE TITLE
[Manager] Ohara 0.10.0 UI

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4521]
Related to #4498 

- Workspace settings
  - [x] Layout @konekoya (#4525)
  - [x] Topic Page @eechih #4584 
  - [x] Autofill Page @eechih #4590
  - [x] Zookeeper Nodes Page @eechih #4599
  - [x] Broker Nodes Page @eechih #4586
  - [x] Worker Nodes Page @eechih #4581 
  - [x] Worker Plugins Page @eechih 
  - [x] Stream Jars Page  @eechih 
  - [x] Workspace Nodes Page @eechih #4527 
  - [x] Workspace Files Page @eechih #4596
  - [x] Restart Confirm Dialog @eechih 
  - [x] Delete Confirm Dialog @eechih 
  - [x] Restart Indicator  @eechih 

- Create workspace
  - [x] Remove Plugins Step @eechih #4522 

- Delete workspace
  - [x] Delete Confirm Dialog(#4650) @wu87988622 
  - [x] Delete Progress Dialog(#4650) @wu87988622 
  - [x] Support rollback & retry(#4650)   @wu87988622
  - [x] Rollback Confirm Dialog(#4682) @wu87988622  

- Restart workspace (#3510)
  - [x] Restart Confirm Dialog(#4682) @wu87988622 
  - [x] Restart Progress Dialog(#4682) @wu87988622 
  - [x] Support rollback & retry(#4682) @wu87988622 
  - [x] Rollback Confirm Dialog(#4682) @wu87988622 
  - [x] Apply new settings(#4682) @wu87988622 
	
- Integrate Shabondi
  - [x] Api & Epic @saivirtue #4520
  - [x] Show in toolbox @saivirtue #4610
  - [x] Add to pipeline @saivirtue  #4636
  - [x] ~~Remove from pipeline @saivirtue~~ (Releated to #4636)
  - [x] ~~Start and stop Shabondi @saivirtue~~ (Releated to #4636)
  - [x] ~~Edit and view properties @saivirtue~~ (Releated to #4636)
