### ISSUE TITLE
Ohara 0.11.0 Release

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4684]
## 1. Schedule
🚴‍♂️  Start: 2020/05/29 (Fri)
❄️  Frozen: 2020/07/10 (Fri)
🐞  Testing & Fix bug: 2020/07/13 (Mon)
🎉  Release: 2020/07/31 (Mon)

### Planning & Design
  - [x] Design wireframe of Ohara Volume
  - [ ] Design 資料追踪
### Backend
  - [x] Enable Java 11 runtime support
  - [ ] Shabondi error handling
  - [x] JDBC Source connector for the multi task
  - [x] Added mount volume to create pod for the K8SClient and DockerClient

### Frontend
  - [x] Refine Restart workspace
  - [x] End-to-end testing
  - [x] Bug fix

## 3. Highlights
- Drop JDK 8 support and migrate to JDK 11 (#4026)
- Upgrade gradle from 6.5 to 6.5.1 (#5390)
- Introduce Ohara Volume (#4621 #5322)
- OharaStream docs improvement (#5099)
- Introduce new document building tools and docs skeleton (#5149)
- Support to deploy JDBC source connector on multiple nodes (#4847)
- Generate a summary report to PR for then frontend (#5301)
- Add a new task for tests of UI flow (#5143)
- Create E2E tests for the new UI (#5096)
- Refine Restart workspace (#5139)

##  4. ToDo
  - [x] fork 0.11.x branch (#5428)
  - [x] Make sure jenkins is able to build and test on both 0.11.x and 0.12.x branches
  - [x] Change 0.11.0-SNAPSHOT to 0.12.0-SNAPSHOT for master branch (#5430)
  - [x] Deploy to demo environment
  - [x] Create Ohara product testing report issue (#5374)
  - [x] Create a new release draft in GitHub's release page
  - [x] Change 0.11.0-SNAPSHOT to 0.11.0 for 0.11.x branch (#5535)
  - [x] Build and Upload Ohara jars to Bintray repo
  - [x] Add tag to release wiki page
  - [x] Build and upload 0.11's binary files to the release draft we created earlier
  - [x] Change 0.11.0 to 0.11.1-SNAPSHOT for 0.11.x branch (#5538)
  - [x] Remove all 0.11.0-SNAPSHOT images from docker hub
