### ISSUE TITLE
Wrapping streamApp java API to use row data type

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#474]
StreamApp java api use the default <key, value> data pair as same as apache kafka, and provide user a option to set "one source code for different kafka environment" (see below):
```java
/* Ohara Env : */
OStream.builder()
  .toOharaEnvStream();
/* Other Kafka Env : */
OStream.builder()
  .bootstrapServers("your_broker_list")
  .appid("simple-application-for-external")
  .fromTopicWith("consume_topic_name", Serdes.STRING, Serdes.ROW)
  .toTopic("target_topic_name")
  .build();
```
This is flexible but also causes the following problems:
1. support different environment means difficult to maintain all the flexibility
2. it is hard to integrate the data type with other components in current version support
3. it may happens that user goes "wrong way" with `builder` (ex : mixing usage of `toOharaEnvStream` and `bootstrapServers` ; the former will overwrite the latter)

We need to ease the overhead for further developers and reduce the complexity of source code, the following tasks are raised to solve this:
- [x] remove the support for other env which is barely uses (#1071)
- [x] change the java api generic type `<K, V>` to `Row` (#1077)
- [x] change the streamApp doc to fit the changes (#1162)
- [x] check if there was any api could not support this changes

required by #1053

**Comment by saivirtue** [comment]
ping @vitojeng @chia7712 
As the discussion last week, I add some comments is the description, could you give some thoughts about this?

**Comment by chia7712** [comment]
> As the discussion last week, I add some comments is the description, could you give some thoughts about this?

LGTM

補充一下：
streamapp能否封裝到讓使用者全程使用row? 如果做得到對現階段很好，因為我們可以延後面對any type帶來的許多工作，進而專心處理我們現在還是0的部份（例如streamapp setting, metrics等等）。但是！如果對streamapp的封裝而言使用row是不合理（或是很難作到）的事情，那我們就把支援any type這件事情提早拉到檯面上並且作為0.5 (或是0.6)的核心項目

**Comment by saivirtue** [comment]
> streamapp能否封裝到讓使用者全程使用row? 
This basically is doable for the current supported streamApp java APIs.
I will add a task to trace the survey work, and if there was an api which is hard to achieve this unfortunately, the api will be marked as **unsupported in current version** and we can implement after the `any type` is constructed.

**Comment by vitojeng** [comment]
I'm +1.

IMO, fully support Row type in streamapp without key value is the highest priority.
I believe some user would happy on this. 😄 

If there have any concern during this task implementation, just call a meeting.

**Comment by saivirtue** [comment]
all done.
