### ISSUE TITLE
[Manager] Address various issues in metrics

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5079]
- [x] Tweak pipeline metrics update logic (#5183)
  - Metrics switch should defaults to off
  - The switch should control metrics visibility and starting/stopping API request

- [x] Fix metrics not correctly handle error issue (#5209)
  - Stop displaying metrics loading message when the request is failed
  - Display the metrics fetch error in event log and snackbar
- [x] Update metrics should not updating unrelated components 
- [x] Recover the metrics update mechanism from HTTP request errors (#5222)

**Comment by konekoya** [comment]
@vitojeng I've added two tasks to address metrics is not loaded issue you just reported :)

**Comment by vitojeng** [comment]
@konekoya That's awesome! Thanks for great support.

**Comment by jackyoh** [comment]
ping @konekoya 這個議題可以關閉了嗎？

**Comment by vitojeng** [comment]
@jackyoh 再等我一天... ^^

**Comment by jackyoh** [comment]
OK, 收到了。我沒注意到 QA 的部份

**Comment by vitojeng** [comment]
QA passed.
