### ISSUE TITLE
[Manager] Create E2E tests for the new UI - Phase III

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5096]
This is the follow-up of #4049

**Pipeline Related**
- [x] Fix skipped pipeline e2e tests (@konekoya) (#5220)

**Workspace Related**
- [x] Add tests to verify settings of workspace works normally (#5112)
- [x] Add tests to verify delete workspace works normally (#5136)
- [x] Reviewed skipped e2e tests (#5144)

**Comment by konekoya** [comment]
All sub tasks related to Paper were moved to #5153 :)
