### ISSUE TITLE
OharaStream docs improvement

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5099]
This is a large task and will address following document related issues:
* Not familiar the RST format, Markdown still is the No.1 choice.
* Sphinix is too complex, hard to customize for us
* Readthedocs is good platform, but we cannot customize the document build phase.
* Refactor the docs structure and more content.
* Add Chinese version.

ToDos
- [x] v0.11.x
  - [x] Introduce new document building tools and docs skeleton(#5149)
  - [x] Migration tasks
    - [x] Quickstart VM(oharastream/ohara-docs#4, oharastream/ohara-docs#17)
    - [x] Ohara document(oharastream/ohara-docs#22)
  - [x] Remove the stale docs builder(#5163)
  - [x] Update docs related content(#5282)
  - [x] Useful shortcodes(oharastream/ohara-docs#38, oharastream/ohara-docs#45)
