### ISSUE TITLE
[Manager] Bump manager dependencies

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5106]
After 0.10 is release, this is a good time to upgrade our deps.

- [x] Bump Manager server dependencies (#5138)
- [x] Bump Manager client dependencies (#5154)
- [x] Bump NodeJS and Yarn versions (#5185)
- [x] Fix wrong yarn version in docker files (#5199)
- [ ] Rebuild deps, ci and manager docker images and verify these images are working correctly

**Comment by konekoya** [comment]
@eechih I remember you mention about upgrading Mui, right.

**Comment by eechih** [comment]
沒錯，麻煩 material-UI/lab 也要更新喔

**Comment by konekoya** [comment]
> 沒錯，麻煩 material-UI/lab 也要更新喔

Will do 💪

**Comment by konekoya** [comment]
@oharastream/frontend The upgrade was done. You can now bump your local NodeJS to 0.12.x and Yarn to 1.22.x. You can also stick with the current version for each. It should still work without any issues. Please let me know if you ever run into problems. Thanks :)
