### ISSUE TITLE
[Manager] Refine Restart workspace

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#5139]
- [x] Keep all error messages from API in Event log during restarting workspace #5122 
- [x] Support small scale restart workspace #5175 
- [x] In any case can enter the setting page to use restart workspace #5227 
- [x] Restart workspace display failed  log #5204 
- [x] Restart workspace should refer to the backend data at each step #5148
- [x] Restart workspace restore rollback and retry #5345 
- [x] Settings restartIndicator automatically determines the restart range #5261
- [x] Refactor restart workspace to Finite-state machine #5345 
- [x] ~~The jar with duplicate name of restartWorker can be updated in the state of reuse~~ #5258 
- [x] Add it with restart workspace more case #5413 
- [x] Restart workspace fail need highlight the unstable workspace #5139
