### ISSUE TITLE
[Manager][IT] tests for UI flows

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5153]
**Description**
After #5143, we will able to add more complicated test cases for our UI flow. Also, we need a way to see the coverage range of tests.

**Related tasks**

- [x] Introduce [code coverage](https://docs.cypress.io/guides/tooling/code-coverage.html#Introduction) to our manager code base (#5169)
  - Integrate Cypress + Typescript + Webpack + CRA v3 + Babel + Istanbul
- [x] add UI tests of AppBar (#5210)
- [x] add UI tests for complex devTool operations (#5263)
- Add IT tests for Navigator
    - [x] Add IT tests for pipeline list, outline and new pipeline dialog (#5231)
    - [x] Add general IT tests for settings dialog (#5255)
    - [x] Add IT tests for files of settings dialog (#5326)
    - [x] Add IT test for danger zone of settings dialog (#5305)
- [x] Add IT tests for Toolbar (#5278)
- [x] add IT tests for Toolbox (#5259)
- [x] Add IT tests for Property view (#5292)
- [x] Add route test for 404 and 501 pages (#5362)
- [x] Add IT tests of Property dialog (#5376)
- Add IT tests for Paper
    - [x] Add a test to verify that actions work as expected (#5336)
    - [x] Add a test to verify select cells could link to the correct position of DevTool dialog (#5336)
    - [x] Pipeline-topics have the correct naming logic (T(n)) (#5336)
    - [x] Ensure Paper elements' action buttons are disabled in different status (#5336)
    - [x] Able to save changes automatically (#5336)
    - [x] Link could be removed by either clicking on link or via editing Property dialog (#5336)
- [x] Move E2E tests that are belong to IT tests (#5412)
- [x] Refine the assemble commands to custom commands (duplicated to #5383)
- [x] Add fail and pending test cases for Paper elements
- [x] Add custom cy commands for creating and connecting Paper elements (#5383)
- [x] Prevent users from deleting a pipeline which has running services in it (#5393)

![image](https://user-images.githubusercontent.com/8088616/83584805-c4870e80-a57a-11ea-8f8e-c851461b19d0.png)
