### ISSUE TITLE
[Manager] [Jenkins] Integrate code coverage to QA

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5215]
Relate to #5153

Since our QA has the ability to post the test report, I hope we could leverage this benefit for code coverage report of ohara-manager :)

This issue has to accomplish:
- [x] archive code coverage files to Jenkins (@jackyoh )
   - We save these files under `/ohara/ohara-manager/client/coverage/`
   - after trigger `manager-it` tasks, these files should be generated
   - archive the folder if exists
- [x] fix uncompleted coverage files generated (#5245)
- Combine UT and IT test report
  - [x] generate the report file to the same path for UT and IT (#5337)
- [x] generate a summary report to PR (move to #5301)
- [x] Add the QA testing in docs (move to [ohara-docs](https://github.com/oharastream/ohara-docs/issues/50))

**Comment by jackyoh** [comment]
@saivirtue  我已經把 /ohara/ohara-manager/client/coverage/ 加入到封存了，可以開一隻 PR 來測試看看嗎？

**Comment by saivirtue** [comment]
> @saivirtue 我已經把 /ohara/ohara-manager/client/coverage/ 加入到封存了，可以開一隻 PR 來測試看看嗎？

Sure :)  
You can edit any line in ohara-manager and use command `retry manager-it`

**Comment by jackyoh** [comment]
ok, 我開一個 PR 來測試

**Comment by jackyoh** [comment]
@saivirtue 測試結果如下：
https://builds.is-land.com.tw/job/PreCommit-OHARA/10688/artifact/ohara/ohara-manager/client/coverage/

如果沒問題，我就把測試的 PR 關閉。
