### ISSUE TITLE
[Manager] The APIs used to verify should be called after the execution APIs

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5295]
This is a small part of `startZookeeperEpic.js`:
```js
return zip(
    defer(() => zookeeperApi.start(params)),
    defer(() => zookeeperApi.get(params)).pipe(
...
```
Since `defer()` will wait until the subscription executed, our APIs (promise-based) will be called **simultaneously** to the backend (in this example, **start** and **get** will be triggered at same time).

Thus, we should "wait" the execution APIs (DELETE/START/STOP) finished before do the verify APIs (GET)

Also, it is not necessary to verify an object had been deleted (Thanks @chia7712 to confirm this)

- [x] Apply to broker (will be done in #5396)
- [x] Apply to connector (move to #5416)
- [x] Apply to shabondi (move to #5416)
- [x] Apply to stream (move to #5416)
- [x] Apply to topic (#5414)
- [x] Apply to worker (#5354)
- [x] Apply to zookeeper (will be done in #5396)

**Comment by saivirtue** [comment]
/cc @oharastream/frontend 
This is a change that will affect all the epics, so if have any concern please let me know :)

**Comment by konekoya** [comment]
> Thus, we should "wait" the execution APIs (DELETE/START/STOP) finished before do the verify APIs (GET)

So this is causing some issues 🤔

**Comment by saivirtue** [comment]
> So this is causing some issues 🤔

AFAIK, this will cause some meaningless verified APIs sent to backend
