### ISSUE TITLE
[Manager] Unify the time delay of mock APIs

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5311]
In `__mocks__/brokerApis.ts`:
```
export const create = (params: ServiceBody): Observable<ClusterResponse> =>
  of({
    status: 200,
    title: 'mock create broker data',
    data: { ...(omit(runtimeData, 'state') as ClusterData), ...params },
  }).pipe(delay(2000));

export const remove = (): Observable<BasicResponse> =>
  of({
    status: 200,
    title: 'mock delete broker data',
    data: {},
  }).pipe(delay(1000));
```

We have various delay time and should use the same unit for them (**delay(100)**)

- [x] Apply to broker (will be done in #5396)
- [x] Apply to connector (move to #5415)
- [x] Apply to file (move to #5415)
- [x] Apply to inspect (move to #5415)
- [x] Apply to log (move to #5415)
- [x] Apply to node (move to #5415)
- [x] Apply to pipeline (move to #5415)
- [x] Apply to shabondi (move to #5415)
- [x] Apply to stream (move to #5415)
- [x] Apply to topic (#5414)
- [x] Apply to worker (#5354)
- [x] Apply to workspace (move to #5415)
- [x] Apply to zookeeper (will be done in #5396)

**Comment by vitojeng** [comment]
看起來這個 issue 的陣容頗龐大

**Comment by saivirtue** [comment]
的確，這個是要統一所有測試的邏輯。 
在這邊先記錄下，接下來有空的時候再慢慢些修改
