### ISSUE TITLE
[Manager] Create workspace exception handling

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#5334]
in conclusion:
1. [x] Prevent users from refreshing the browser directly before the long-term task ends #5379 
2. [x] Users can leave long-term tasks that cannot be completed
3. [x] Highlight unusable workspaces #5365 
4. [x] Prevent users to use the unstable workspace #5385 
5. [x] Remind users to continue unfinished tasks -> Move to next milestone
6. [x] Stop the development of the following functions: Suspend, Resume

_Originally posted by @eechih in https://github.com/oharastream/ohara/issues/5321#issuecomment-651494407_
