### ISSUE TITLE
[Manager] Unify the time delay of mock APIs - Phase II

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5415]
Follow-up of #5311 

In `__mocks__/brokerApis.ts`:
```
export const create = (params: ServiceBody): Observable<ClusterResponse> =>
  of({
    status: 200,
    title: 'mock create broker data',
    data: { ...(omit(runtimeData, 'state') as ClusterData), ...params },
  }).pipe(delay(2000));

export const remove = (): Observable<BasicResponse> =>
  of({
    status: 200,
    title: 'mock delete broker data',
    data: {},
  }).pipe(delay(1000));
```

We have various delay time and should use the same unit for them (**delay(100)**)

- [x] Apply to connector (#5509  )
- [x] Apply to file (#5536 )
- [x] Apply to inspect (#5536 )
- [x] Apply to node (#5536 )
- [x] Apply to pipeline (#5536 )
- [x] Apply to shabondi (#5516 )
- [x] Apply to stream (#5516 )
- [x] Apply to workspace  (#5536 )
