### ISSUE TITLE
[Manager] The APIs used to verify should be called after the execution APIs - Phase II

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5416]
follow-up of #5295

This is a small part of `startZookeeperEpic.js`:
```js
return zip(
    defer(() => zookeeperApi.start(params)),
    defer(() => zookeeperApi.get(params)).pipe(
...
```
Since `defer()` will wait until the subscription executed, our APIs (promise-based) will be called **simultaneously** to the backend (in this example, **start** and **get** will be triggered at same time).

Thus, we should "wait" the execution APIs (DELETE/START/STOP) finished before do the verify APIs (GET)

Also, it is not necessary to verify an object had been deleted (Thanks @chia7712 to confirm this)

- [x] Apply to connector (#5509 )
- [x] Apply to shabondi (#5516 )
- [x] Apply to stream  (#5516 )

**Comment by eechih** [comment]
@saivirtue 這個 issue 的項目都完成了，我們應該可以關閉這個 issue :)
