### ISSUE TITLE
Improve jdbc source connector (phase 1)

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#5434]
0.11 實作了 multi task 的部份了 issue #4847 

預計 0.12 的 jdbc source connector 需要實做, 以下的 task:
- [x] Remove variable name of jdbc prefix for the JDBC source connector (#5541)
- [x] Modify variable name and remove unused setting for the jdbc source connector (#5542)
- [x] Avoid using while loop to calculate time range (#5546)
- [x] Added increment setting to the JDBC source connector (#5604 )
- [x] Refactor JDBC source task for the timestamp mode (#5631)
- [x] Support Increment+timestamp qury for the exactly once (#5642)
- [x] Added jdbc source connector integration test for the increment+timestamp mode (#5647)
- [x] Remove the duplicate code for the TimestampQueryHandler and TimestampIncrementQueryHandler (#5649)
- [x] Modify unit test for the TestJDBCSourceConnectorExactlyOnce (#5652)
- [ ] <del>時間寬度可以使用參數來調整</del>

**Comment by chia7712** [comment]
可否連結先前的issue?

**Comment by jackyoh** [comment]
我來加上去

**Comment by chia7712** [comment]
any update?

**Comment by jackyoh** [comment]
我會把剩下，還沒做完的部份移到下個版本。
