### ISSUE TITLE
[Manager] Introduce volume

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#5551]
- [x] Introduce volume api #5572 
- [x] Introduce volume with quick create workspace #5583 
- [ ] Introduce volume with setting page #5641 
- [x] Volume API supports padding missing from path @chia7712  (#5586)

**Comment by wu87988622** [comment]
@chia7712 Need your help~ thanks

**Comment by chia7712** [comment]
> Introduce check whether the path is lega

我記得現在前端會自己管理各服務的volume位置？也就是使用者只指定根目錄（例如/tmp/aa）然後你們會在/tmp/aa下面建立不同目錄給不同服務？

**Comment by wu87988622** [comment]
> > Introduce check whether the path is lega
> 
> 我記得現在前端會自己管理各服務的volume位置？也就是使用者只指定根目錄（例如/tmp/aa）然後你們會在/tmp/aa下面建立不同目錄給不同服務？

是的 只需要幫忙檢查根目錄後續 manager會管理

**Comment by chia7712** [comment]
> 只需要幫忙檢查根目錄後續

這件事情有點尷尬，因為後端不知道前端後續要在該路徑下建立什麼東西，後端會不知道該檢查什麼比較好...

例如，假如該目錄下已經有相關服務的資料夾了，後端是否需要拋錯？

我有一個想法是前端直接嘗試去建立目錄看看（例如隨意建立一個tmp volume當作是否可行？）

**Comment by wu87988622** [comment]
> 我有一個想法是前端直接嘗試去建立目錄看看（例如隨意建立一個tmp volume當作是否可行？）

這樣負擔會很大嗎
因為使者輸入完畢 就會去檢查
那就會
建立->volume
啟動->volume 
來去確認是否可以使用
請問是這樣嗎？

**Comment by chia7712** [comment]
> 這樣負擔會很大嗎

負擔很小，因為volume的建立與啟動只是建立"關聯"而已，真正會有負擔是掛到container時候才會出現

> 建立->volume
啟動->volume

yep

**Comment by wu87988622** [comment]


> > 這樣負擔會很大嗎
> 
> 負擔很小，因為volume的建立與啟動只是建立"關聯"而已，真正會有負擔是掛到container時候才會出現
> 
> > 建立->volume
> > 啟動->volume
> 
> yep

ok 那前端先這樣處理檢查得部分
感謝

**Comment by wu87988622** [comment]
@chia7712 
Because of the front-end requirements, the volume API needs to support the completion of missing paths thanks.
