### ISSUE TITLE
身為一個好的工程師，我希望 collie 的設計與測試可以更加完善

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#651]
- [x] #520 K8SClient class 的 function 需要修改成 future 
- [x] ssh 和 k8s 的 creator 方法相同邏輯的地方放到 ContainerCollie (duplicate to #1045)
- [x] #846 ssh and k8s implementation should have a super class including most common code (將 ssh 和 k8s 的共用邏輯, 放到一個 class裡, 預計 M27 會完成)
- [x] Move all toXXXCluster from ClusterCollie to XXXCollie (moved to issue #1164)
- [x] [Phase 1] Move all creator container common logic from implement class to Collie trait (#1270)
- [x] [Phase 2] Move all creator container common logic from implement class to Collie trait (#1360)
- [x]  [Phase 1] Refactor K8SClient #731
- [x] [Phase 2] Refactor K8sClient #1318
- [x] Adding container name format to Collie for implementing collie the common name #1256
- [x] [Phase 1] Complete tests for ContainerCollie #1083
- [x] [Phase 2] Complete tests for ContainerCollie #1320
- [x] all functions of builder/creator should be covered by unit tests (#1455)
- [x] document all methods in collie (this issue is resolved by other issues)

**Comment by vitojeng** [comment]
Replace story label with the umbrella label

**Comment by chia7712** [comment]
@jackyoh Do you have free cycle to complete the refactor for K8sClient?

**Comment by jackyoh** [comment]
我下週開始來規劃 refactor K8sClient 的部份，預計下一個 MileStone 來完成

**Comment by chia7712** [comment]
all sub-tasks are completed :)
