### ISSUE TITLE
[umbrella] Complete the docs - phase 0

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#681]
It is time to create "docs" folder and then produce following document.
- [x] configurator APIs (moved to issue #701)
- [x] user guide - phase 0 (moved to issue #860)
- [x] custom connector guideline (moved to issue #720)
- [x] custom streamapp guideline (moved to issue #984)
- [x] revise root/readme (moved to issue #714)

This issue has no version label since it is an umbrella issue without any commits to source code. 

FYI @vitojeng @eechih @konekoya @jackyoh @saivirtue

**Comment by saivirtue** [comment]
Oh...I really don't like this task :(

**Comment by chia7712** [comment]
> Oh...I really don't like this task :(

me too :(

**Comment by konekoya** [comment]
No problem. Would love to contribute to this. How can I help though :)
