### ISSUE TITLE
revise root/readme

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#714]
Our readme is a bit ugly since there are too many different kind of description. This issue plan to keep the most important part in root/readm and move other description to docs/.

- [x] move streamapp section from root/readme to docs/custom_streamapp.md (#715)
- [x] complete docs for gradle commands and ohara installation (#854)
- [x] move installation section from root/readme to docs/user_guide (#858)

~move run xxx section from root/readme to docs/?? ~
Keeping gradle commands in root/readme is good to contributors. I don't plan to move it to other docs.

FYI @konekoya @vitojeng @jackyoh @eechih @saivirtue

**Comment by chia7712** [comment]
all tasks are done.
