### ISSUE TITLE
Custom connector guideline

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#720]
This issue aims to write a doc about **how to be a good guy in custom connector world". The expected sections are listed below.
- [x] ohara connector overview (#760)
- [x] source connector (#775)
- [x] sink connector (#815)
- [x] version (#826)
- [x] setting definition (#837)
- [x] add quick links (#852)
- [x] metrics (#850)
- [x] add dependencies description for custom connector (#856)

**Comment by chia7712** [comment]
all done. close this issue.
