### ISSUE TITLE
separate the docker client logic from stream router

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#723]
This issue address following tasks:
- [x] refactor stream router to be more readable #754 
- [x] support k8s in stream router #808
- [x] change request body of stream APIs #751
- [x] Update streamApp docs #761
- [x] pipeline id should not use in stream router url #762
- [x] ~use same rule of worker cluster name for streamApp name #741~

**Comment by saivirtue** [comment]
all related tasks are finished, will closed this issue
