### ISSUE TITLE
Add e2e tests in pipeline page

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#752]
Add e2e tests for most of the pipeline components

- [x] Refactor and clean up old frontend e2e test suites #764 
- [x] Add e2e tests to verify that users are able to add new topics into a pipeline graph #768 
- [x] Add e2e tests to verify that users are able to add new streamApp into a pipeline graph #777 
- [x] Add e2e tests to verify that users can add new connectors into pipelines #784 
- [x] Add e2e tests to verify that users can see the correct relation between connectors in the pipeline graph #823 
- [x] Add e2e tests to verify that users can save graph after adding/removing new connectors #806 

required by #645

**Comment by konekoya** [comment]
All the sub-tasks have been closed. Bugs and follow up refactor will be tracked in separate issues respectively
