### ISSUE TITLE
Enhance streamApp to support custom setting

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#810]
like #480 did, we need to make streamApp more flexible in settings.

This issue has the following tasks:
- [x] Support custom configs for streamApp (#1726)
-  Change the interface of `start()` to accept parameters (**OStream**, **ConfigDef**)
-  Config is like `SettingDefinition` (should extend JSON serialize / deserialize)
-  ConfigDef should manage the Config class
-  Add new abstract method `ConfigDef config()` for user to define configurations
- [x] Support custom config for stream API (#1929)
- [x] change prefix from stream to streams (move to issue #2115)
