### ISSUE TITLE
add Type.Duration to connector

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#853]
Duration is a common type in setting of connector. Ohara ought to support the type via offering following mechanism. 

- [x] Add Type.Duration and Validator (#921)
- [x] apply Type.Duration to PerfSource (#931)
- [x] support the scala.Duration representation (#946) (FYI @eechih )
- [x] add more docs about the string format for Duration (#955)

**Comment by chia7712** [comment]
FYI @eechih

**Comment by chia7712** [comment]
@eechih Do you want to take over the issue " apply Type.Duration to PerfSource"??

**Comment by eechih** [comment]
OK

**Comment by chia7712** [comment]
@eechih Thanks! Noted that our kafka wrapper is based on java. The duration format is based on java.Duration as well. The conversion of scala.Duration is not compatible with java.Duration.

**Comment by chia7712** [comment]
all are completed.
