### ISSUE TITLE
Run all the frontend end to end tests on CI

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#874]
CI should be able to run all the frontend tests against each PR

- [x] Make sure CI can run frontend e2e tests with gradle it command (#894)
- [x] Use cypress.env.json config if there's one in the local (#971 )
- [x] Start and clean services for running all frontend e2e tests (#966 )
- [x] Rename gradle properties for manager IT tests (#898) 
- [x] ohara-manager:it should depend on ohara-it:jar rather than ohara-it:build (#906)
Depending on ohara-it:jar can avoid the useless tasks of ohara-it
- [x] ohara-manager should clone the streamapp jar from ohara-it rather than storing a stale jar in git repo (#971)
#770 had introduced the task of generating streamapp in ohara-it.

**Comment by chia7712** [comment]
@wu87988622 Please help us to finish this issue.

**Comment by wu87988622** [comment]
> @wu87988622 Please help us to finish this issue.

Ok I got it.

**Comment by chia7712** [comment]
I have to fix the issue "ohara-manager:it should depend on ohara-it:jar rather than ohara-it:build"...

**Comment by chia7712** [comment]
@konekoya @wu87988622 麻煩確實的**完整**描述裏的相關連結 為了現在的RM 也為了以後的讀者好 適當的連結可以加速追蹤相關議題

**Comment by chia7712** [comment]
@konekoya Could we close this issue?

**Comment by konekoya** [comment]
> @konekoya @wu87988622 麻煩確實的完整描述裏的相關連結 為了現在的RM 也為了以後的讀者好 適當的連結可以加速追蹤相關議題

No problem :)

**Comment by wu87988622** [comment]
> @konekoya @wu87988622 麻煩確實的**完整**描述裏的相關連結 為了現在的RM 也為了以後的讀者好 適當的連結可以加速追蹤相關議題

好的
