### ISSUE TITLE
Refactor Crane

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#885]
Since `Crane` has a lot of similar logic with `Collie`, we need to merge the crane to collie.
There are some tasks must be done :
- [x] Refactor crane to collie (issue #904)
- [x] Refactor stream route to be more tidy (issue #968)
- [x] Remove the ssh.Cache from crane (moved to issue #1023)

block by #846

**Comment by saivirtue** [comment]
all done!
