### ISSUE TITLE
Update sbt configuration

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#893]
Phase 1 of #1044 

- [x] update all dependencies(#981)
- [x] add ohara-metrics module(#981)
- [x] run junit from sbt(#981)
- [x] generate VersionUtis.java dynamically(#994)
