### ISSUE TITLE
Fix frontend flaky e2e tests

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#895]
Some frontend e2e tests are not very stable.

- [x] Fix frontend streamApp failing e2e tests #895
- [x] Fix worker e2e flaky tests #895
- [x] Fix brokers, pipeline List page and workers pages flaky tests #987 
- [x] Rewrite services initializing and cleanup logic in cypress #920
