### ISSUE TITLE
[Umbrella] Complete the pre-check for setting of connector

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#919]
Ohara offers many setting type to connector developers to **define** their custom settings. Connector user can see the failure quickly if we can pre-check the value according to type before truly starting connector.

- [x] Add custom check for Type.Table (moved to issue #886)
- [x] add Type.Duration to connector (moved to issue #853)
- [x] Disable connectors to retrieve the raw configs, and force them to use default conversion provided by TaskConfig (#935)

The check of type, which is supported by kafka, is up to kafka :)

**Comment by chia7712** [comment]
all sub-issues are resolved.
