### ISSUE TITLE
A generic cache implementation for all slow data operations

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#974]
We have completed enough functions for ohara and it is time to care for latency. A quick solution is to provide cache for all slow (data) operations, such as topic, pipeline and connector APIs. 

- [x] a generic cache implementation (#985)
- [x] apply cache to topic APIs (#992)
- [x] apply cache to connector APIs (#997)
- [x] apply cache to pipeline APIs (#1003)
- [x] apply cache to collie (#1019)

#1023 is the follow-up which removes ssh.Cache actually.

**Comment by saivirtue** [comment]
> a generic cache implementation
Will this interface be placed in `common` module?

**Comment by chia7712** [comment]
> Will this interface be placed in common module?

Yep. It will replace all cache code in ohara
