### ISSUE TITLE
[Umbrella] Add custom streamapp guideline

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#984]
This issue address to write a document about **how to write a custom streamApp**. The expected sections are listed below.
- [x] ohara streamApp overview (issue #682)
- [x] streamApp entry (issue #682)
- [ ] streamApp java api #963
- [ ] setting definition #962
- [ ] add quick links #962
- [ ] metrics #962
